### ISSUE TITLE
High CPU after Upgrade to 1.2.0

### ISSUE THREAD

**Issue by celevra** [crowdsecurity/crowdsec#1022]
Hi,

after Upgrade to 1.2.0 i got high cpu load (300%).
there are no log entries that are guiding me to the right solution.
i'm not sure wich informations you need to dig into Problem

```
crowdsec # cscli hub list
INFO[23-10-2021 11:44:22 PM] dependency of crowdsecurity/nginx : sub collection crowdsecurity/base-http-scenarios is broken : missing scenarios crowdsecurity/http-crawl-non_statics, tainted.
INFO[23-10-2021 11:44:22 PM] dependency of crowdsecurity/base-http-scenarios : missing scenarios crowdsecurity/http-crawl-non_statics, tainted.
INFO[23-10-2021 11:44:22 PM] Loaded 23 collecs, 28 parsers, 36 scenarios, 3 post-overflow parsers
INFO[23-10-2021 11:44:22 PM] PARSERS:
-------------------------------------------------------------------------------------------------------------
 NAME                            📦 STATUS   VERSION  LOCAL PATH
-------------------------------------------------------------------------------------------------------------
 crowdsecurity/dateparse-enrich  ✔️  enabled  0.1      /etc/crowdsec/parsers/s02-enrich/dateparse-enrich.yaml
 crowdsecurity/geoip-enrich      ✔️  enabled  0.2      /etc/crowdsec/parsers/s02-enrich/geoip-enrich.yaml
 crowdsecurity/sshd-logs         ✔️  enabled  1.0      /etc/crowdsec/parsers/s01-parse/sshd-logs.yaml
 crowdsecurity/http-logs         ✔️  enabled  0.6      /etc/crowdsec/parsers/s02-enrich/http-logs.yaml
 crowdsecurity/nginx-logs        ✔️  enabled  0.8      /etc/crowdsec/parsers/s01-parse/nginx-logs.yaml
 crowdsecurity/mysql-logs        ✔️  enabled  0.2      /etc/crowdsec/parsers/s01-parse/mysql-logs.yaml
 crowdsecurity/whitelists        ✔️  enabled  0.2      /etc/crowdsec/parsers/s02-enrich/whitelists.yaml
 crowdsecurity/syslog-logs       ✔️  enabled  0.4      /etc/crowdsec/parsers/s00-raw/syslog-logs.yaml
-------------------------------------------------------------------------------------------------------------
INFO[23-10-2021 11:44:22 PM] SCENARIOS:
--------------------------------------------------------------------------------------------------------------------------
 NAME                                       📦 STATUS   VERSION  LOCAL PATH
--------------------------------------------------------------------------------------------------------------------------
 crowdsecurity/ssh-bf                       ✔️  enabled  0.1      /etc/crowdsec/scenarios/ssh-bf.yaml
 crowdsecurity/ssh-slow-bf                  ✔️  enabled  0.2      /etc/crowdsec/scenarios/ssh-slow-bf.yaml
 ltsich/http-w00tw00t                       ✔️  enabled  0.1      /etc/crowdsec/scenarios/http-w00tw00t.yaml
 crowdsecurity/http-path-traversal-probing  ✔️  enabled  0.2      /etc/crowdsec/scenarios/http-path-traversal-probing.yaml
 crowdsecurity/http-sqli-probing            ✔️  enabled  0.2      /etc/crowdsec/scenarios/http-sqli-probing.yaml
 crowdsecurity/http-bad-user-agent          ✔️  enabled  0.4      /etc/crowdsec/scenarios/http-bad-user-agent.yaml
 crowdsecurity/http-generic-bf              ✔️  enabled  0.1      /etc/crowdsec/scenarios/http-generic-bf.yaml
 crowdsecurity/mysql-bf                     ✔️  enabled  0.1      /etc/crowdsec/scenarios/mysql-bf.yaml
 crowdsecurity/http-backdoors-attempts      ✔️  enabled  0.2      /etc/crowdsec/scenarios/http-backdoors-attempts.yaml
 crowdsecurity/http-open-proxy              ✔️  enabled  0.2      /etc/crowdsec/scenarios/http-open-proxy.yaml
 crowdsecurity/http-probing                 ✔️  enabled  0.2      /etc/crowdsec/scenarios/http-probing.yaml
 crowdsecurity/http-xss-probing             ✔️  enabled  0.2      /etc/crowdsec/scenarios/http-xss-probing.yaml
--------------------------------------------------------------------------------------------------------------------------
INFO[23-10-2021 11:44:22 PM] COLLECTIONS:
--------------------------------------------------------------------------------------------------------------------
 NAME                               📦 STATUS           VERSION  LOCAL PATH
--------------------------------------------------------------------------------------------------------------------
 crowdsecurity/mysql                ✔️  enabled          0.1      /etc/crowdsec/collections/mysql.yaml
 crowdsecurity/nginx                ✔️  enabled          0.1      /etc/crowdsec/collections/nginx.yaml
 crowdsecurity/base-http-scenarios  ⚠️  enabled,tainted  0.5      /etc/crowdsec/collections/base-http-scenarios.yaml
 crowdsecurity/linux                ✔️  enabled          0.2      /etc/crowdsec/collections/linux.yaml
 crowdsecurity/sshd                 ✔️  enabled          0.2      /etc/crowdsec/collections/sshd.yaml
--------------------------------------------------------------------------------------------------------------------
INFO[23-10-2021 11:44:22 PM] POSTOVERFLOWS:
--------------------------------------
 NAME  📦 STATUS  VERSION  LOCAL PATH
--------------------------------------
--------------------------------------
```

```
cat /etc/crowdsec/config.yaml
common:
  daemonize: true
  pid_dir: /var/run/
  log_media: file
  log_level: info
  log_dir: /var/log/
  working_dir: .
config_paths:
  config_dir: /etc/crowdsec/
  data_dir: /var/lib/crowdsec/data/
  simulation_path: /etc/crowdsec/simulation.yaml
  hub_dir: /etc/crowdsec/hub/
  index_path: /etc/crowdsec/hub/.index.json
  notification_dir: /etc/crowdsec/notifications/
  plugin_dir: /usr/lib/crowdsec/plugins/
crowdsec_service:
  acquisition_path: /etc/crowdsec/acquis.yaml
  parser_routines: 1
cscli:
  output: human
db_config:
  log_level: warn
  type: sqlite
  db_path: /var/lib/crowdsec/data/crowdsec.db
  #user:
  #password:
  #db_name:
  #host:
  #port:
  flush:
    max_items: 5000
    max_age: 7d
plugin_config:
  user: nobody # plugin process would be ran on behalf of this user
  group: nogroup # plugin process would be ran on behalf of this group
api:
  client:
    insecure_skip_verify: false
    credentials_path: /etc/crowdsec/local_api_credentials.yaml
  server:
    log_level: warn
    listen_uri: 0.0.0.0:8181
    profiles_path: /etc/crowdsec/profiles.yaml
    online_client: # Crowdsec API credentials (to push signals and receive bad IPs)
      credentials_path: /etc/crowdsec/online_api_credentials.yaml
#    tls:
#      cert_file: /etc/crowdsec/ssl/cert.pem
#      key_file: /etc/crowdsec/ssl/key.pem
prometheus:
  enabled: true
  level: full
  listen_addr: 127.0.0.1
  listen_port: 6060
```

```
==> /var/log/crowdsec.log <==
time="23-10-2021 23:40:22" level=info msg="loading acquisition file : /etc/crowdsec/acquis.yaml"
time="23-10-2021 23:40:22" level=info msg="Adding file /var/log/nginx/error.log to datasources" type=file
time="23-10-2021 23:40:22" level=info msg="Adding file /var/log/nginx/access.log to datasources" type=file
time="23-10-2021 23:40:22" level=info msg="Adding file /var/log/auth.log to datasources" type=file
time="23-10-2021 23:40:22" level=info msg="Adding file /var/log/syslog to datasources" type=file
time="23-10-2021 23:40:22" level=info msg="Adding file /var/log/kern.log to datasources" type=file
time="23-10-2021 23:40:22" level=info msg="Reload is finished"
time="23-10-2021 23:40:22" level=warning msg="Starting processing data"
time="23-10-2021 23:42:21" level=info msg="Signal push: 1 signals to push"
time="23-10-2021 23:45:21" level=info msg="Signal push: 1 signals to push"
```

![image](https://user-images.githubusercontent.com/232437/138572523-9bb95009-c61c-44c3-945b-7f00d6468e70.png)

let me know if you need anything
