### ISSUE TITLE
Bug/Hidden dependency on `crowdsecurity/syslog-logs` parser

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#106]
**Describe the bug**
the `crowdsecurity/syslog-logs` parser is required for crowdsec to run normally, but it's not explicitly said.
If I want to parse non-syslog Nginx logs, this parser is required, but it's not explicit. (or else 'nginx' won't be in the right field)

**To Reproduce**
 - Install crowdsec without `crowdsecurity/syslog-logs` parser
 - Try to read nginx logs file (not in one-shot)
 - Doesn't work

**Technical Information (please complete the following information):**
 - Version: 0.2.2

**Comment by erenJag** [comment]
This part of the `crowdsecurity/syslog-logs` 
```yaml
#if it's not syslog, the type is the progname
filter: "evt.Line.Labels.type != 'syslog'"
onsuccess: next_stage
name: crowdsecurity/non-syslog
#debug: true
statics:
  - parsed: message
    expression: evt.Line.Raw
  - parsed: program
    expression: evt.Line.Labels.type
```

Should be implemented in the parser : if no parser match in the first stage => apply those statics and send to next stage.
