### ISSUE TITLE
Bug/journalctl source prevents clean reload/exit

### ISSUE THREAD

**Issue by ThinkChaos** [crowdsecurity/crowdsec#1061]
**Describe the bug**
When I enable a journalctl source, crowdsec no longer reloads/exits properly when I use systemctl to stop/restart it.

**To Reproduce**
1. Add a journalctl source:
```yaml
source: journalctl
journalctl_filters:
 - "_SYSTEMD_UNIT=ssh.service"
labels:
  type: syslog
```
2. `systemctl reload crowdsec` to enable that source
3. `systemctl reload crowdsec` to reproduce: it will hang and systemd will kill it with SIGKILL after some time

**Technical Information (please complete the following information):**
 - OS: `Linux 5.4.0-4-amd64 #1 SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux`
 - Version: `v1.2.1-debian-pragmatic-linux-dd03d073558e380c283afe66942f537c3da647ff`
