### ISSUE TITLE
Improvement/Ability to take action against a range that is *not* the IP's official range

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#1152]
cf. https://discourse.crowdsec.net/t/is-it-possible-to-monitor-subnet-instead-of-ip-s/498/3

User asked (and it sounds like a great idea) to be able to take action against the `/24` of an IP, and not necessarily the range provided by the [geoip-enrich](https://hub.crowdsec.net/author/crowdsecurity/configurations/geoip-enrich) plugin.

**Proposal**

Currently, scenario can already specify a made-up scope and value :

```yaml
type: leaky
name: crowdsecurity/foobar
...
scope:
  type: something
  expression: evt.Meta.username
```

Thus simply having a `expr` [helper](https://doc.crowdsec.net/docs/next/expr/helpers/) allowing to round up an IP to a given range (ipv4/ipv6) size might do the trick ?

**Example** 

We would then end-up with (needs refinement for proper ipv6 handling, but you get the idea)

```yaml
type: leaky
name: crowdsecurity/distributed-something-something
description: "fight distributed stuff"
filter: "evt.Parsed.service = 'smth' and ..."
groupby: "evt.Meta.SourceRange"
distinct: "evt.Meta.source_ip"
capacity: 5
leakspeed: "10s"
blackhole: 5m
labels:
 service: http
 type: scan
 remediation: true
scope:
  type: Range
  expression: IpToRange(evt.Parsed.Source_ip, "/24")
```
