### ISSUE TITLE
Bug/ingress-nginx bouncer issue

### ISSUE THREAD

**Issue by rlex** [crowdsecurity/crowdsec#1214]
**Describe the bug**
Tried to install bouncer as per this article https://doc.crowdsec.net/docs/v1.2/bouncers/ingress-nginx/

However, i can't pull image due to it asking for creds (private image, private registry?)

It seems like there is another image available: https://hub.docker.com/r/crowdsecurity/lua-bouncer-plugin

However, with it plugins fails to run with 

```
2022/01/28 11:48:50 [error] 33#33: [lua] plugins.lua:19: load_plugin(): error loading plugin "plugins.crowdsec.main": /etc/nginx/lua/plugins/crowdsec/crowdsec.lua:37: attempt to index field 'cache' (a nil value)

```

**To Reproduce**
Install ingress-nginx bouncer but use 
```
image: crowdsecurity/lua-bouncer-plugin
```

**Expected behavior**
Plugin should init and run

**Comment by he2ss** [comment]
Hi @rlex,

Thanks for you multiple feedbacks. Indeed there was a typo in the documentation, I just updated it.
Here is the repo of the official docker image : https://hub.docker.com/r/crowdsecurity/lua-bouncer-plugin
So it's `crowdsecurity/lua-bouncer-plugin` instead of `crowdsec-lua`.

**Comment by he2ss** [comment]
I tested it locally, it seems working. 
Did you installed you ingress nginx from official helm chart ?

**Comment by rlex** [comment]
Yep, this one https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx

**Comment by he2ss** [comment]
Could you please use this one and tell me if it's working ? I just added the lua-shared-dict config.

```yaml
controller:
  extraVolumes:
  - name: crowdsec-bouncer-plugin
    emptyDir: {}
  extraInitContainers:
  - name: init-clone-crowdsec-bouncer
    image: crowdsecurity/lua-bouncer-plugin
    imagePullPolicy: IfNotPresent
    env:
      - name: API_URL
        value: "http://crowdsec-service.crowdsec.svc.cluster.local:8080" # crowdsec lapi service-name
      - name: API_KEY
        value: "<API KEY>" # generated with `cscli bouncers add -n <bouncer_name>
      - name: DISABLE_RUN
        value: "true"
      - name: BOUNCER_CONFIG
        value: "/crowdsec/crowdsec-bouncer.conf"
    command: ['sh', '-c', "sh /docker_start.sh; mkdir -p /lua_plugins/crowdsec/; cp /crowdsec/* /lua_plugins/crowdsec/"]
    volumeMounts:
    - name: crowdsec-bouncer-plugin
      mountPath: /lua_plugins
  extraVolumeMounts:
  - name: crowdsec-bouncer-plugin
    mountPath: /etc/nginx/lua/plugins/crowdsec
    subPath: crowdsec
  config:
    plugins: "crowdsec"
    lua-shared-dicts: "crowdsec_cache: 50m"
```

I'll update the crowdsec documentation about that. 
Thanks for the feedback !
