### ISSUE TITLE
Bug/Adding rdns whitelists does not work as described in docs

### ISSUE THREAD

**Issue by ThomasLohner** [crowdsecurity/crowdsec#122]
**Describe the bug**
I wanted to whitelist our servers which all have a rdns record. As per this [doc](https://doc.crowdsec.net/write_configurations/whitelist/) i created a file `./config/parsers/s02-enrich/my_whitelists.yaml`:
```
name: my/whitelists
description: "Whitelist events from my servers"
whitelist:
  reason: "my server"
  expression:
    - "'scalecommerce.rocks' in evt.Meta.source_ip_rdns"
```

Now crowdsec **fails** with:
```
FATA[06-07-2020 17:58:38] Unable to compile whitelist expression ''scalecommerce.rocks' in evt.Meta.source_ip_rdns' : invalid operation: in (mismatched types string and string) (1:23)
 | 'scalecommerce.rocks' in evt.Meta.source_ip_rdns
 | ......................^.  id=shy-forest name=scalecommerce/whitelists stage=s02-enrich
```

However this syntax does not throw an exception:
```
  expression:
    - "evt.Meta.source_ip_rdns endsWith 'scalecommerce.rocks'"
```

**Questions**
1. What's the difference between `evt.Meta.source_ip.rdns` and `evt.Enriched.reverse_dns` (which is used by [crowdsecurity/seo-bots-whitelist](https://hub.crowdsec.net/author/crowdsecurity/configurations/seo-bots-whitelist))?
1. When to put stuff in `parsers/s02-enrich/` and when in `postoverflows/s01/`?
 
**To Reproduce**
1. Add expression filter on rdns to whitelist
2. restart crowdsec

**Expected behavior**
I think there should be some better documentation of what data fields are available and how expressions work.

**Technical Information (please complete the following information):**
 - Version v0.2.3
