### ISSUE TITLE
Bug/crowdsec : in whitelist config, statics are applied even if the whitelist not succeed 

### ISSUE THREAD

**Issue by erenJag** [crowdsecurity/crowdsec#124]
**Describe the bug**
In a whitelist configuration, if we want to add a static in `meta`, the static will be applied even if the whitelist not succeed.

**To Reproduce**
```yaml
# cat /etc/crowdsec/config/parsers/s02-enrich/mywhitelists.yaml
name: crowdsecurity/whitelists
description: "Whitelist events from my ip addresses"
debug: true
whitelist:
  reason: "my ip ranges"
  ip:
    - "1.2.3.4"
statics:
  - meta: toto
    value: lol
```

**Expected behavior**
The statics should be applied only if the whitelist is a success
