### ISSUE TITLE
Bug/crowdsec.service yaml parsing error with GROK patterns

### ISSUE THREAD

**Issue by baudneo** [crowdsecurity/crowdsec#1246]
Bug/cscli: issue with `pattern_syntax` and multiple patterns AND/OR grok patterns %{SPACE} %{MONTHNUM} - unclear

**Describe the bug**
This example code throws errors
```
pattern_syntax:
  GOTIFY_DATE: %{YEAR}/%{MONTHNUM}/%{NUMBER}\s[\-]\s%{TIME}
  GOTIFY_SEPERATOR: %{SPACE}\|%{SPACE}
  GOTIFY_401: ^\[GIN\]%{SPACE}%{GOTIFY_DATE}%{GOTIFY_SEPERATOR}401%{GOTIFY_SEPERATOR}%{DATA:request_time_took}%{GOTIFY_SEPERATOR}%{IP:source_ip}%{GOTIFY_SEPERATOR}%{WORD:request_type}%{SPACE}\"%{DATA:endpoint}\"
nodes:
  - grok:
      name: "GOTIFY_401"
      apply_on: message
      statics:
        - meta: log_type
          value: gotify_failed_auth
statics:
  - meta: source_ip
    expression: evt.Parsed.source_ip
```
While this does not
```
  GOTIFY_DATE: \d*/\d*/\d*\s[\-]\s.*
  GOTIFY_SEPERATOR: \s*\|\s*
  GOTIFY_401: ^\[GIN\]\s*%{GOTIFY_DATE}%{GOTIFY_SEPERATOR}401%{GOTIFY_SEPERATOR}%{DATA:request_time_took}%{GOTIFY_SEPERATOR}%{IP:source_ip}%{GOTIFY_SEPERATOR}%{WORD:request_type}\s*\"%{DATA:endpoint}\"
```

**To Reproduce**
Add the first example into a parser config and restart crowdsec, there will be a yaml error about 'token cant start with' or similar.

**Expected behavior**
GROK patterns were debugged using heroku grok debugger and then copied into gotify configs. There is obviously some sort of parsing error inside of crowdsec or whatever it is using for grok (go grokker?)

**Technical Information (please complete the following information):**
 - OS: debian bullseye
 - Version 
 ```
❯ cscli version
2022/02/08 03:53:08 version: v1.2.3-debian-pragmatic-a6e405422c732e9b6c46ae1004a2b80297df8336
2022/02/08 03:53:08 Codename: alphaga
2022/02/08 03:53:08 BuildDate: 2022-01-11_10:15:01
2022/02/08 03:53:08 GoVersion: 1.17.5
2022/02/08 03:53:08 Constraint_parser: >= 1.0, <= 2.0
2022/02/08 03:53:08 Constraint_scenario: >= 1.0, < 3.0
2022/02/08 03:53:08 Constraint_api: v1
2022/02/08 03:53:08 Constraint_acquis: >= 1.0, < 2.0
```
![grok_dbg](https://user-images.githubusercontent.com/86508179/152973952-b5fd330c-6b09-40aa-98dc-59308852366c.png)
