### ISSUE TITLE
Bug/crowdsec.service hangs when systemctl restart or host reboot/shutdown

### ISSUE THREAD

**Issue by baudneo** [crowdsecurity/crowdsec#1247]
**Describe the bug**
crowdsec times out when using systemctl restart or when shutting down the host. crowdsec.service hangs until killed by the systemd timeout. I have debug logs enabled that provide no information on why, syslogs also hold no clues as to why.

**To Reproduce**
Steps to reproduce the behaviour:
`systemctl restart crowdsec.service`
`shutdown now`
`reboot`

**Expected behaviour**
crowdsec should restart and or shutdown without hanging until timeout or killed

**Screenshots**

**Technical Information (please complete the following information):**
 - OS: debian bullseye
 - Version 1.2.3
```
2022/02/08 03:53:08 version: v1.2.3-debian-pragmatic-a6e405422c732e9b6c46ae1004a2b80297df8336
2022/02/08 03:53:08 Codename: alphaga
2022/02/08 03:53:08 BuildDate: 2022-01-11_10:15:01
2022/02/08 03:53:08 GoVersion: 1.17.5
2022/02/08 03:53:08 Constraint_parser: >= 1.0, <= 2.0
2022/02/08 03:53:08 Constraint_scenario: >= 1.0, < 3.0
2022/02/08 03:53:08 Constraint_api: v1
2022/02/08 03:53:08 Constraint_acquis: >= 1.0, < 2.0
```

**Comment by blotus** [comment]
Hello,

Can you provide the content of `/etc/crowdsec/acquis.yaml` ?

Can you post the logfile somewhere ? We should be able to use to see where crowdsec hangs.

**Comment by baudneo** [comment]
`acquis.yaml`

```
#Generated acquisition file - wizard.sh (service: nginx) / files :
journalctl_filter:
 - _SYSTEMD_UNIT=nginx.service
labels:
  type: nginx
---
#Generated acquisition file - wizard.sh (service: sshd) / files : /var/log/auth.log
filenames:
  - /var/log/auth.log
labels:
  type: syslog
---
#Generated acquisition file - wizard.sh (service: mysql) / files :
journalctl_filter:
 - _SYSTEMD_UNIT=mysql.service
labels:
  type: mysql
---
#Generated acquisition file - wizard.sh (service: linux) / files : /var/log/syslog /var/log/kern.log /var/log/messages
filenames:
  - /var/log/syslog
  - /var/log/kern.log
  - /var/log/messages
labels:
  type: syslog
---
# NPM Logs
filenames:
  - /root/data/logs/proxy-host-*_*.log
  - /root/data/logs/default_host.log
  - /root/data/logs/fallback*.log

labels:
  type: nginx
---
#Generated acquisition file - wizard.sh (service: sshd) / files : /var/log/auth.log
filenames:
  - /var/log/auth.log
labels:
  type: syslog
---
#Generated acquisition file - wizard.sh (service: mysql) / files :
journalctl_filter:
 - _SYSTEMD_UNIT=mysql.service
labels:
  type: mysql
---
#Generated acquisition file - wizard.sh (service: linux) / files : /var/log/syslog /var/log/kern.log /var/log/messages
filenames:
  - /var/log/syslog
  - /var/log/kern.log
  - /var/log/messages
labels:
  type: syslog
---
# Gotify STDOUT logs
filenames:
  - /root/gotify_data/gotify.log
labels:
  type: gotify
```

The log file is 97MB lol, I left debug logging on and forgot! -> [here](https://1drv.ms/u/s!AvkrxIqRvG4Mn35og6-Gn1Qz6jsT?e=I9Fcj7)
