### ISSUE TITLE
Bucket is full but Crowdsec didn't block it

### ISSUE THREAD

**Issue by phamleduy04** [crowdsecurity/crowdsec#1306]
I tried to DDOS myself to check if crowdsec block my IP or not
```
time="03-03-2022 20:22:42" level=debug msg="bucket 'phamleduy04/http-ddos' is poured" cfg=wispy-shadow file=/etc/crowdsec/scenarios/http-ddos.yaml name=phamleduy04/http-ddos
time="03-03-2022 20:22:42" level=debug msg="Uniq(<MY REAL IP>) : ko, discard event" bucket_id=summer-snow capacity=30 cfg=wispy-shadow file=/etc/crowdsec/scenarios/http-ddos.yaml name=phamleduy04/http-ddos partition=eb032c3bff7f99fd9f91e95162186d8d6fc6048b
```

I'm not sure this is a bug or a misconfig by myself so I didn't put in bugs. 

this is my `http-ddos` file
```yaml
type: leaky
format: 1.0
debug: true
name: phamleduy04/http-ddos
description: "test"
filter: "evt.Meta.source_ip != ''"
groupby: "evt.Meta.source_ip"
distinct: "evt.Meta.source_ip"
capacity: 30
leakspeed: "30s"
blackhole: 5m
labels:
  type: scan
  remediation: true
```

and this is my docker-compose file

```yml
version: '3.8'
services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    environment:
      GID: "${GID-1000}"
      #Dominic-Wagner/vaultwarden-bf Dominic-Wagner/vaultwarden-logs crowdsecurity/whitelists crowdsecurity/whitelist-good-actors
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/base-http-scenarios"
    volumes:
      - ./config/acquis.yaml:/etc/crowdsec/acquis.yaml
      - crowdsec-db:/var/lib/crowdsec/data/
      - crowdsec-config:/etc/crowdsec
      - traefik_traefik-logs:/var/log/traefik/:ro
      - ./http-ddos.yaml:/etc/crowdsec/scenarios/http-ddos.yaml:ro
    networks:
      - proxy
    restart: unless-stopped

  bouncer-traefik:
    image: docker.io/fbonalair/traefik-crowdsec-bouncer:latest
    container_name: bouncer-traefik
    environment:
      CROWDSEC_BOUNCER_API_KEY: <DELETED>
      CROWDSEC_AGENT_HOST: crowdsec:8080
    networks:
      - proxy
    depends_on:
      - crowdsec
    restart: unless-stopped

  dashboard:
    image: phamleduy04/crowdsec-dashboard:latest
    container_name: crowdsec-dashboard
    ports:
      - 3030:3000
    environment:
      MB_DB_FILE: /data/metabase.db
      MGID: "${GID-1000}"
    depends_on:
      - 'crowdsec'
    volumes:
      - crowdsec-db:/metabase-data/
    restart: unless-stopped

networks:
  proxy:
    external: true

volumes:
  crowdsec-db:
  crowdsec-config:
  traefik_traefik-logs:
    external: true
```
