### ISSUE TITLE
Bug/Fatal CrowdSec Agent failed to start when parsers are missing

### ISSUE THREAD

**Issue by erdoukki** [crowdsecurity/crowdsec#1362]
CrowdSec Agent failed to start and crash with a FATAL logged, when the host miss some scenarios and parsers.

```
time="16-03-2022 17:34:47" level=warning msg="Loaded 5 scenarios"
time="16-03-2022 17:34:47" level=info msg="loading acquisition file : /etc/crowdsec/acquis.yaml"
time="16-03-2022 17:34:47" level=warning msg="No matching files for pattern /var/log/nginx/*.log" type=file
time="16-03-2022 17:34:47" level=warning msg="No matching files for pattern ./tests/nginx/nginx.log" type=file
time="16-03-2022 17:34:47" level=warning msg="No matching files for pattern /var/log/auth.log" type=file
time="16-03-2022 17:34:47" level=warning msg="No matching files for pattern /var/log/syslog" type=file
time="16-03-2022 17:34:47" level=fatal msg="crowdsec init: Error while loading acquisition config : while loading acquisition configuration: while configuring datasource of type file from /etc/crowdsec/acquis.yaml: failed to configure datasource file: Cannot parse FileAcquisition configuration: yaml: unmarshal errors:\n  line 4: cannot unmarshal !!str `/var/lo...` into []string"
```
with a custom (global) config acquis.yaml:
```
filenames:
  - /var/log/nginx/*.log
  - ./tests/nginx/nginx.log
#this is not a syslog log, indicate which kind of logs it is
labels:
  type: nginx
---
filenames:
 - /var/log/auth.log
 - /var/log/syslog
labels:
  type: syslog
---
filename: /var/log/apache2/*.log
labels:
  type: apache2
---
filenames:
  - /var/log/system.log
labels:
  type: syslog
```

Make a FATAL because of "missing" (not installed) scenarios and  parsers !

May be we may prefer a WARNING than a FATAL (and crash) ?

Partly the same as;
https://github.com/crowdsecurity/cs-firewall-bouncer/issues/150#issuecomment-1069297635

> It's only a suggest, but, when you want a "generic" configuration, like on some embedded devices, you'll get also end-users impacts, and while users may not have access to the devices itself, or do not care to made complicate and manual configuration, we stand for a no working or complicate auto-configuration, while, another working mode more "global", may help to catch most of the cases...
