### ISSUE TITLE
improvement/IP whitelist

### ISSUE THREAD

**Issue by KarelWintersky** [crowdsecurity/crowdsec#1614]
Is any way to add some IPs to whitelist for SSH-BF Scenario?

**Comment by LaurenceJJones** [comment]
Hey I haven't tested any of this but if you try below and then reload crowdsec

You can create something like this create /etc/crowdsec/parsers/s02-enrich/mywhitelists.yaml
```yaml
name: crowdsecurity/whitelists
description: "Whitelist events from sshd"
filter: "evt.Parsed.program == 'sshd'"
whitelist:
  reason: "Dont ban IP"
  ip:
    - "MYIP"
    - "IP2"
```
Keep in mind this will whitelist for program sshd not just BF scenario if you wanted that you would need to change the filter to
```
"evt.Meta.log_type == 'ssh_failed-auth'"
```
