### ISSUE TITLE
Bug/HTTP plugin: Not all notifications go to Elasticsearch

### ISSUE THREAD

**Issue by waster** [crowdsecurity/crowdsec#1618]
**Describe the bug**
Not all notifications go to Elasticsearch with HTTP plugin.

**To Reproduce**
1. nginx-req-limit-exceeded scenario:
```
type: leaky
name: crowdsecurity/nginx-req-limit-exceeded
description: "Detects IPs which violate nginx's user set request limit."
filter: evt.Meta.sub_type == 'req_limit_exceeded'
leakspeed: "60s"
capacity: 30
groupby: evt.Meta.source_ip
blackhole: 5m
labels:
 service: nginx
 type: bruteforce
 remediation: true
```
2. Notification plugin configured with Elasticsearch and enabled in default profile:

_http.yaml:_
```
type: http
name: es_default
log_level: trace
format: |-
  {{ range .}}
   {"index": { "_index": "crowdsec", "_type" : "_doc" } }
   {{.|toJson}}
  {{ end }}
url: http://127.0.0.1:9200/_bulk
method: POST
headers:
  Content-Type: "application/x-ndjson"
skip_tls_verification: true
```
_profiles.yaml:_
```
name: default_ip_remediation
debug: true
filters:
 - Alert.Remediation == true && Alert.GetScope() == "Ip"
decisions:
 - type: ban
   duration: 4h
notifications:
    - es_default
on_success: break
---
name: notify_only
filters:
 - Alert.Remediation == false && Alert.GetScope() == "Ip"
notifications:
    - es_default
on_success: break
```
2. Generate error.log with rate limit messages to trigger scenario

For example I run test for 1 minute to trigger 10 alerts with ban decisions and fake IPs.

cscli:
![image](https://user-images.githubusercontent.com/2188440/176432166-50f1add2-b733-49a1-9be7-d5920d181bf6.png)

But only 5 of them go to the ES:
![image](https://user-images.githubusercontent.com/2188440/176432306-da195095-63bf-44a3-9231-4ef454cdfd76.png)

Warn messages in the log:
```
time="29-06-2022 15:04:23" level=warning msg="Cannot send alert to Plugin channel"
time="29-06-2022 15:04:23" level=warning msg="Cannot send alert to Plugin channel"
time="29-06-2022 15:04:23" level=warning msg="Cannot send alert to Plugin channel"
time="29-06-2022 15:04:23" level=warning msg="Cannot send alert to Plugin channel"
time="29-06-2022 15:04:23" level=warning msg="Cannot send alert to Plugin channel"
```

**Technical Information:**
 - OS: Centos 7.6
 - Elasticsearch 6.8
 - CrowdSec 1.3.4
