### ISSUE TITLE
Support environment variable expansion in email plugin config file

### ISSUE THREAD

**Issue by ggiammat** [crowdsecurity/crowdsec#1726]
### What would you like to be added?

I would like to use an env variable in the email plugin configuration file (e.g., for the smtp_password key). Something like this:
```yaml
type: email
...
smtp_host: mymailserver.exampl.org
smtp_username: username
smtp_password: ${SMTP_PASSWORD}
smtp_port: 587
...
```

This feature is already supported in the main Crowdsec config file (https://docs.crowdsec.net/docs/configuration/crowdsec_configuration/#environment-variables), but apparently not for the plugins configuration files.

### Why is this needed?

This can be particularly useful in Docker and Kubernetes deployments  in order to not have secrets directly in the config files, but inject them at runtime.

In my case, I have deployed Crowdsec in Kubernetes using the [ Helm chart](https://github.com/crowdsecurity/helm-charts). To configure the email plugin, I had to specify the password in my Helm values file (in the `config.notifications` value), while I would like to use an env variable for the password and then set the env variable in the lapi pod using a secret. Something like this:

```yaml
lapi:
  env:
    - name: SMTP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: crowdsec-smtp-password
          key: password

config:
  notifications:
    email.yaml: |
      type: email
      ...
      smtp_host: mymailserver.exampl.org
      smtp_username: username
      smtp_password: ${SMTP_PASSWORD}
      smtp_port: 587
```
