### ISSUE TITLE
container_name_regexp only supports 1 wildcard

### ISSUE THREAD

**Issue by sharkymcdongles** [crowdsecurity/crowdsec#1778]
### What happened?

The name for container_name_regexp is misleading and behavior is undocumented fully. The containers are found fine when I set it to:

`container_name_regexp:  k8s_controller_ingress-nginx-controller*`

However, if I set it as follows it finds nothing:

`container_name_regexp:  k8s_controller_ingress-nginx-controller*_ingress-nginx_*`

### What did you expect to happen?

I would expect both to work. I would also think it would be cool if it actually had full regexp instead of just glob support since the name says regexp.

### How can we reproduce it (as minimally and precisely as possible)?

Try using 2 or more * for container_name_regexp.

### Crowdsec version

<details>
1.14.1
</details>

### OS version

<details>
running containerized on k8s with the docker sock mounted via a modified version of the official helm chart, so it is this image:

 crowdsecurity/crowdsec:v1.4.1
</details>

### Enabled collections and parsers

N/A

### Acquisition config

Works:
```
  acquis.yaml: |-
    ---
    source: docker
    container_name_regexp:
     - k8s_controller_ingress-nginx-controller*
    labels:
      type: ingress-nginx
      program: ingress-nginx
    follow_stdout: true
    follow_stderr: false
    docker_host: unix:///run/docker.sock
```

Fails:
```
  acquis.yaml: |-
    ---
    source: docker
    container_name_regexp:
     - k8s_controller_ingress-nginx-controller*_ingress-nginx_*
    labels:
      type: ingress-nginx
      program: ingress-nginx
    follow_stdout: true
    follow_stderr: false
    docker_host: unix:///run/docker.sock
```

Container Name Example: 
```
k8s_controller_ingress-nginx-controller-5894d4f79-7k7c9_ingress-nginx_b1cf68d5-8129-4ee0-9fc8-e8f7baafd45b_0
```

### Config show

N/A

### Prometheus metrics

N/A

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

N/A
