### ISSUE TITLE
Support sampling at acquisition level

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#1856]
### What would you like to be added?

I would like to have the ability to force crowdsec's acquisition to perform sampling on logs based on the amount of EP/s.
This parameter should be able to be controlled by the user per file or at least per acquisition section. 

Something like this : 

```yaml
filename: /var/log/nginx-error.log
labels:
  type: nginx
sampling:
 - threshold: 1000 # eps
   value: 100%
 - threshold: 10000 # eps
   value: 80%
 - threshold: 100000 # eps
   value: 50%

```

The example config should properly be challenged to be more user-friendly or draw inspiration from existing systems. Still, the idea is to allow users to set thresholds that trigger random sampling on logs.

### Why is this needed?

When facing massive DoS/DDoS, the amount of logs to be ingested is too high for crowdsec to keep up with.
Using this approach will allow to mitigate the "lag" that crowdsec might accumulate while reading the file.

The reason behind this strategy is that : 
 - If crowdsec starts to "fall behind" the tail of the logs, it's a lost battle
 - When facing DoS or DDoS, performing sampling on the data will still provide more or less the same results
