### ISSUE TITLE
CrowdSec doesn't raise issues in Kubernetes Cluster

### ISSUE THREAD

**Issue by Aptul9** [crowdsecurity/crowdsec#1976]
### What happened?

Hi everyone,
I have recently tried to set up a Kubernetes cluster with Ingress-Nginx and CrowdSec.
I have followed this guide posted in CrowdSec: https://www.crowdsec.net/blog/kubernetes-crowdsec-integration
However, I think some parts are missing, such as the ingress file, which I set up by myself.
Everything seems to be working fine, CrowdSec has access to the logs produced by ingress-nginx, but when I try to use Nikto, no alerts get raised:
![image](https://user-images.githubusercontent.com/48324233/211278429-51b4d762-e818-4ea0-86a6-598377594f45.png)
I have tried everything, but I could not identify the issue.
The only change I made was that I am not using AWS, therefore I have omitted the file

`ingress-nginx-values.yaml`

### What did you expect to happen?

I expected CrowdSec to raise an alert

### How can we reproduce it (as minimally and precisely as possible)?

My configuration is just the basic one from the CrowdSec tutorial

### Crowdsec version

crowdsec:latest

### OS version

Default Container

**Comment by LaurenceJJones** [comment]
Could you upload or send some sample lines of the log entries from the file shown in metrics.

**Comment by Aptul9** [comment]
Yes, sure!
I have now tried to get the logs directly from the ingress-nginx-controller:
`kubectl -n ingress-nginx logs ingress-nginx-controller-666f45c794-x9lh9`
The following was the response:
```
192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] "GET /forum/index.php?method=&lt;script&gt;alert('Vulnerable')&lt;/script&gt; HTTP/1.1" 200 13 "-" "Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001453)" 206 0.000 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.001 200 2a26a0e93c9d8f6dce96c62d63d23ccc
192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] "GET /zorum/index.php?method=&lt;script&gt;alert('Vulnerable')&lt;/script&gt; HTTP/1.1" 200 13 "-" "Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001454)" 206 0.001 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.000 200 5a540ee5a99de29207049dc2a8c152b3
192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] "GET /wwwboard/passwd.txt HTTP/1.1" 200 13 "-" "Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001455)" 154 0.000 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.001 200 64904dbc8a5507a1efe93fc1fde69e8e
192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] "GET /login/sm_login_screen.php?error=\x5C\x22><script>alert('Vulnerable')</script> HTTP/1.1" 200 13 "-" "Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001456)" 206 0.000 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.000 200 488b4872fda45a330df98b5bab1e38cc
192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] "GET /login/sm_login_screen.php?uid=\x5C\x22><script>alert('Vulnerable')</script> HTTP/1.1" 200 13 "-" "Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001457)" 204 0.001 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.001 200 069c146addee0ff8afa808cb850e3ce6
192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] "GET /SPHERA/login/sm_login_screen.php?error=\x5C\x22><script>alert('Vulnerable')</script> HTTP/1.1" 200 13 "-" "Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001458)" 213 0.000 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.000 200 e7ef9252a71f411b060f8e9c9fca6501
192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] "GET /SPHERA/login/sm_login_screen.php?uid=\x5C\x22><script>alert('Vulnerable')</script> HTTP/1.1" 200 13 "-" "Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001459)" 211 0.000 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.001 200 d02388179e6c6500164500eeff2397a3
192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] "GET /acart2_0/signin.asp?msg=<script>alert(\x5C\x22test\x5C\x22)</script> HTTP/1.1" 200 13 "-" "Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001460)" 191 0.000 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.001 200 82ecd68a84a39bf4236781a73cf75047
192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] "GET /ows-bin/perlidlc.bat?&dir HTTP/1.1" 200 13 "-" "Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001461)" 160 0.000 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.000 200 c9dbfb62fa2809a7c416a174d5f71ce4
192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] "GET /photo/ HTTP/1.1" 200 13 "-" "Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001462)" 141 0.001 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.001 200 e377a768cf08def8441c7084461b539e
192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] "GET /photodata/ HTTP/1.1" 200 13 "-" "Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001463)" 145 0.000 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.000 200 cdfe81d9996d9d0a64dcbe9ff967027e
192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] "GET /iissamples/issamples/oop/qfullhit.htw?CiWebHitsFile=/iissamples/issamples/oop/qfullhit.htw&CiRestriction=none&CiHiliteType=Full HTTP/1.1" 200 13 "-" "Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001465)" 262 0.000 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.000 200 d58dfa0d51827126a4acf8d0156904b1
192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] "GET /iissamples/issamples/oop/qsumrhit.htw?CiWebHitsFile=/iissamples/issamples/oop/qsumrhit.htw&CiRestriction=none&CiHiliteType=Full HTTP/1.1" 200 13 "-" "Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001466)" 262 0.000 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.001 200 4044bc8b23c0e642ea2ec12555f6fa84
192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] "GET /null.htw?CiWebHitsFile=/default.asp%20&CiRestriction=none&CiHiliteType=Full HTTP/1.1" 200 13 "-" "Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001467)" 210 0.001 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.000 200 275ecd45c144dd50b3dec5aaa8c38ea8
```
Those are obviously just a few lines.
I have then tried to get the logs directly from the pod:
`cat /var/log/containers/ingress-nginx-controller-666f45c794-x9lh9_ingress-nginx_controller-7079a53a77e039e63f138e296190038b115a36cc3757bc9a16a16b6b0bae3ec7.log`

And I got a similar response:
```
{"log":"192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] \"GET /login/sm_login_screen.php?uid=\\x5C\\x22\u003e\u003cscript\u003ealert('Vulnerable')\u003c/script\u003e HTTP/1.1\" 200 13 \"-\" \"Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001457)\" 204 0.001 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.001 200 069c146addee0ff8afa808cb850e3ce6\n","stream":"stdout","time":"2023-01-09T11:21:57.5723674Z"}
{"log":"192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] \"GET /SPHERA/login/sm_login_screen.php?error=\\x5C\\x22\u003e\u003cscript\u003ealert('Vulnerable')\u003c/script\u003e HTTP/1.1\" 200 13 \"-\" \"Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001458)\" 213 0.000 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.000 200 e7ef9252a71f411b060f8e9c9fca6501\n","stream":"stdout","time":"2023-01-09T11:21:57.5967833Z"}
{"log":"192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] \"GET /SPHERA/login/sm_login_screen.php?uid=\\x5C\\x22\u003e\u003cscript\u003ealert('Vulnerable')\u003c/script\u003e HTTP/1.1\" 200 13 \"-\" \"Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001459)\" 211 0.000 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.001 200 d02388179e6c6500164500eeff2397a3\n","stream":"stdout","time":"2023-01-09T11:21:57.6193103Z"}
{"log":"192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] \"GET /acart2_0/signin.asp?msg=\u003cscript\u003ealert(\\x5C\\x22test\\x5C\\x22)\u003c/script\u003e HTTP/1.1\" 200 13 \"-\" \"Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001460)\" 191 0.000 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.001 200 82ecd68a84a39bf4236781a73cf75047\n","stream":"stdout","time":"2023-01-09T11:21:57.6392712Z"}
{"log":"192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] \"GET /ows-bin/perlidlc.bat?\u0026dir HTTP/1.1\" 200 13 \"-\" \"Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001461)\" 160 0.000 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.000 200 c9dbfb62fa2809a7c416a174d5f71ce4\n","stream":"stdout","time":"2023-01-09T11:21:57.6590058Z"}
{"log":"192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] \"GET /photo/ HTTP/1.1\" 200 13 \"-\" \"Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001462)\" 141 0.001 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.001 200 e377a768cf08def8441c7084461b539e\n","stream":"stdout","time":"2023-01-09T11:21:57.6804483Z"}
{"log":"192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] \"GET /photodata/ HTTP/1.1\" 200 13 \"-\" \"Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001463)\" 145 0.000 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.000 200 cdfe81d9996d9d0a64dcbe9ff967027e\n","stream":"stdout","time":"2023-01-09T11:21:57.6997088Z"}
{"log":"192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] \"GET /iissamples/issamples/oop/qfullhit.htw?CiWebHitsFile=/iissamples/issamples/oop/qfullhit.htw\u0026CiRestriction=none\u0026CiHiliteType=Full HTTP/1.1\" 200 13 \"-\" \"Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001465)\" 262 0.000 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.000 200 d58dfa0d51827126a4acf8d0156904b1\n","stream":"stdout","time":"2023-01-09T11:21:57.7207606Z"}
{"log":"192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] \"GET /iissamples/issamples/oop/qsumrhit.htw?CiWebHitsFile=/iissamples/issamples/oop/qsumrhit.htw\u0026CiRestriction=none\u0026CiHiliteType=Full HTTP/1.1\" 200 13 \"-\" \"Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001466)\" 262 0.000 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.001 200 4044bc8b23c0e642ea2ec12555f6fa84\n","stream":"stdout","time":"2023-01-09T11:21:57.7402461Z"}
{"log":"192.168.65.3 - - [09/Jan/2023:11:21:57 +0000] \"GET /null.htw?CiWebHitsFile=/default.asp%20\u0026CiRestriction=none\u0026CiHiliteType=Full HTTP/1.1\" 200 13 \"-\" \"Mozilla/5.00 (Nikto/2.1.6) (Evasions:None) (Test:001467)\" 210 0.001 [default-helloworld-5678] [] 10.1.0.201:5678 13 0.000 200 275ecd45c144dd50b3dec5aaa8c38ea8\n","stream":"stdout","time":"2023-01-09T11:21:57.7584533Z"}
```
I also provide my current configuration, just in case:
Ingress.yaml:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
spec:
  defaultBackend:
    service:
      name: helloworld
      port:
        number: 5678
  ingressClassName: nginx
  rules:
  - host: nginxtest.local
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: helloworld
              port:
                number: 5678
```
the crowdsec-values.yaml file is the same of the official guide.

Thank you for your support!

**Comment by LaurenceJJones** [comment]
So unless you disable the [default whitelist](https://hub.crowdsec.net/author/crowdsecurity/configurations/whitelists) your current IP will not be detected.

You can include `crowdsecurity/whitelists` in the `DISABLE_PARSERS` in your values.yaml

**Comment by Aptul9** [comment]
Yes, I have tried to run them locally, the tests were run from the same IP.
I expected there was some whitelist for the local IPs, but I didn't know where to configure them.
I have seen the link above, however, the file is huge, with many env parameters.

Is it possible to add this environment variable in the crowdsec-values.yaml to make it easier?
```
agent:
  # To specify each pod you want to process it logs (pods present in the node)
  acquisition:
    # The namespace where the pod is located
    - namespace: ingress-nginx
      # The pod name
      podName: ingress-nginx-controller-*
      # as in crowdsec configuration, we need to specify the program name so the parser will match and parse logs
      program: nginx
  # Those are ENV variables
  env:
  # As it's a test, we don't want to share signals with CrowdSec so disable the Online API.
  - name: DISABLE_ONLINE_API
    value: "true"
  # As we are running Nginx, we want to install the Nginx collection
  - name: COLLECTIONS
    value: "crowdsecurity/nginx"
lapi:
  env:
    # As it's a test, we don't want to share signals with CrowdSec, so disable the Online API.
    - name: DISABLE_ONLINE_API
      value: "true"
```
Maybe in the agent or lapi section?

**Comment by LaurenceJJones** [comment]
So in the end the value.yaml should look like
```
agent:
  # To specify each pod you want to process it logs (pods present in the node)
  acquisition:
    # The namespace where the pod is located
    - namespace: ingress-nginx
      # The pod name
      podName: ingress-nginx-controller-*
      # as in crowdsec configuration, we need to specify the program name so the parser will match and parse logs
      program: nginx
  # Those are ENV variables
  env:
  # As it's a test, we don't want to share signals with CrowdSec so disable the Online API.
  - name: DISABLE_ONLINE_API
    value: "true"
  # As we are running Nginx, we want to install the Nginx collection
  - name: COLLECTIONS
    value: "crowdsecurity/nginx"
  - name: DISABLE_PARSERS
    value: "crowdsecurity/whitelists"
lapi:
  env:
    # As it's a test, we don't want to share signals with CrowdSec, so disable the Online API.
    - name: DISABLE_ONLINE_API
      value: "true"
```
We should include it commented out in the master file, cause unless you know the "difference" between agent and lapi it hard to know which environment to provide it too.

**Comment by Aptul9** [comment]
Hi, it seems to be working now:
![image](https://user-images.githubusercontent.com/48324233/211330127-7c6f6ae8-b97c-4802-8028-a157a6cf2d0d.png)
I get alerts and decisions, however, we run the command
`cscli bouncers add ingress-nginx`
inside the pod itself, so what happens if the pods get deleted or it stops? Do I have to run everything once again?
Also, even if crowdsec takes the decision, for some reason, the IP that ban (Ip:192.168.65.3), is not my actual IP, which is 192.168.8.165, so might there be some other kind of misconfiguration?

**Comment by LaurenceJJones** [comment]
For this you would use the `BOUNCER_KEY_<CUSTOM_NAME_HERE>` environment variable in the LAPI ENV. So for your example it would be

- name: `BOUNCER_KEY_ingess-nginx`
  value: "YZqmvJe2hmXy7fHV3jgYm7oLSiibCBRu"
  
Then on the bouncer you would enter the API key of `YZqmvJe2hmXy7fHV3jgYm7oLSiibCBRu`

**Comment by Aptul9** [comment]
Hi, thank you a lot!
I have now found what the error was: when I run the command
`helm -n ingress-nginx upgrade -f crowdsec-ingress-bouncer.yaml ingress-nginx ingress-nginx/ingress-nginx`
The ingress-nginx controller fails to create, the error is the following:
![image](https://user-images.githubusercontent.com/48324233/212080317-0ab11078-a659-47db-9e24-4d39d1082e49.png)
![image](https://user-images.githubusercontent.com/48324233/212080469-2edaabe2-34b8-4bf0-a81c-b8f240415821.png)
I have looked online, but I was not able to find a solution, I have even tried other pcs.
I suspect that Kubernetes kills the pod because it doesn't initialize fast enough

**Comment by LaurenceJJones** [comment]
Hmm I would suggest looking at the logs to see if there anything in there. Also I can see why the IP might have not been the remote from within the logs if you are using minikube it depends on how you are accessing the application as you can open a proxied port.

**Comment by Aptul9** [comment]
I have tried both Windows, Linux and GKE Host, I can't see the logs because the pod is not in a startup status, however the error I keep getting is always the same...

**Comment by Aptul9** [comment]
I have the standard crowdsec-ingress-bouncer.yaml and I apply it with the command:
`helm -n ingress-nginx upgrade -f crowdsec-ingress-bouncer.yaml ingress-nginx ingress-nginx/ingress-nginx`
Just in case, this is the file from the official guide:
```
controller:
  extraVolumes:
  - name: crowdsec-bouncer-plugin
    emptyDir: {}
  extraInitContainers:
  - name: init-clone-crowdsec-bouncer
    image: crowdsecurity/lua-bouncer-plugin
    imagePullPolicy: IfNotPresent
    env:
      - name: API_URL
        value: "http://crowdsec-service.crowdsec.svc.cluster.local:8080"
      - name: API_KEY
        value: "ea85226aee37ff012345b084898df895"
      - name: DISABLE_RUN
        value: "true"
      - name: BOUNCER_CONFIG
        value: "/crowdsec/crowdsec-bouncer.conf"
    command: ['sh', '-c', "sh /docker_start.sh; mkdir -p /lua_plugins/crowdsec/; cp /crowdsec/* /lua_plugins/crowdsec/"]
    volumeMounts:
    - name: crowdsec-bouncer-plugin
      mountPath: /lua_plugins
  extraVolumeMounts:
  - name: crowdsec-bouncer-plugin
    mountPath: /etc/nginx/lua/plugins/crowdsec
    subPath: crowdsec
  config:
    plugins: "crowdsec"
    lua-shared-dicts: "crowdsec_cache: 50m"
```
Might you try to replicate the issue?
