### ISSUE TITLE
Init:CrashLoopBackOff on ingress-nginx bouncer

### ISSUE THREAD

**Issue by thatsimo** [crowdsecurity/crowdsec#1992]
### What happened?

When I try to start the ingress-nginx with the provided file in the official guide i get the following error

```
❯ kubectl get pods -n ingress-nginx
NAME                                        READY   STATUS                  RESTARTS      AGE
ingress-nginx-controller-7fd6d69f78-c7zhg   0/1     Init:CrashLoopBackOff   2 (19s ago)   46s
```

and then if i try to describe the pod status, I get the following error

```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  96s                default-scheduler  Successfully assigned ingress-nginx/ingress-nginx-controller-7fd6d69f78-c7zhg to docker-desktop
  Normal   Pulling    95s                kubelet            Pulling image "crowdsecurity/lua-bouncer-plugin"
  Normal   Pulled     86s                kubelet            Successfully pulled image "crowdsecurity/lua-bouncer-plugin" in 9.304550879s
  Normal   Pulled     42s (x3 over 85s)  kubelet            Container image "crowdsecurity/lua-bouncer-plugin" already present on machine
  Normal   Created    41s (x4 over 86s)  kubelet            Created container init-clone-crowdsec-bouncer
  Normal   Started    41s (x4 over 86s)  kubelet            Started container init-clone-crowdsec-bouncer
  Warning  BackOff    12s (x7 over 84s)  kubelet            Back-off restarting failed container
```

I cannot show the log pod because the pod doesn't start at all.

Of course I followed the official guide https://www.crowdsec.net/blog/kubernetes-crowdsec-integration-remediation

### What did you expect to happen?

I expect the pod to start

### How can we reproduce it (as minimally and precisely as possible)?

Just follow apply the yaml as described in the official documentation linked above.

### Crowdsec version

latest

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>

**Comment by LaurenceJJones** [comment]
Just a quick read over the article: Does your yaml have `yaml=` at the top?

```yaml
yaml= 
controller:
   extraVolumes: 
       - name: crowdsec-bouncer-plugin. 
          emptyDir: {}
```

If so, this isn't needed, and you need to remove it. It's probably our website not formatting the code correctly

**Comment by LaurenceJJones** [comment]
Just a quick read over the article: Does your yaml have `yaml=` at the top?

```yaml
yaml= 
controller:
   extraVolumes: 
       - name: crowdsec-bouncer-plugin. 
          emptyDir: {}
```

If so, this isn't needed, and you need to remove it. It's probably our website not formatting the code correctly

**Comment by thatsimo** [comment]
Hi Laurence, of course there's no `yaml=` at the top. 

Here's my `crowdsec-ingress-bouncer.yaml` yaml, runned with `helm -n ingress-nginx install -f crowdsec-ingress-bouncer.yaml ingress-nginx ingress-nginx/ingress-nginx --create-namespace`

```
controller:
  extraVolumes:
  - name: crowdsec-bouncer-plugin
    emptyDir: {}
  extraInitContainers:
  - name: init-clone-crowdsec-bouncer
    image: crowdsecurity/lua-bouncer-plugin
    imagePullPolicy: IfNotPresent
    env:
      - name: API_URL
        value: "http://crowdsec-service.crowdsec.svc.cluster.local:8080"
      - name: API_KEY
        value: "pq234fi9l337ff012345h784804rfd83"
      - name: DISABLE_RUN
        value: "true"
      - name: BOUNCER_CONFIG
        value: "/crowdsec/crowdsec-bouncer.conf"
    command: ['sh', '-c', "sh /docker_start.sh; mkdir -p /lua_plugins/crowdsec/; cp /crowdsec/* /lua_plugins/crowdsec/"]
    volumeMounts:
    - name: crowdsec-bouncer-plugin
      mountPath: /lua_plugins
  extraVolumeMounts:
  - name: crowdsec-bouncer-plugin
    mountPath: /etc/nginx/lua/plugins/crowdsec
    subPath: crowdsec
  config:
    plugins: "crowdsec"
    lua-shared-dicts: "crowdsec_cache: 50m"
```
