### ISSUE TITLE
DB URL cannot have unsafe characters

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec#2007]
### What happened?

Testing for multi server workshop on monday and my database password was random characters , however, golang url parse fails on `#` in my case.

```
db_config:
  type: pgx
  user: crowdsec
  ##password: "NfWdKd#tqCD$yL632Rci"
  password: "YeiqVOUv6H6Z3XPMIE1o"
  db_name: crowdsec
  host: 127.0.0.1
  port: 5432
```

We either need to handle this edge case or pre warn users they cant use that character (dont think we should do this)

### What did you expect to happen?

Pre warn users they can use special characters in password or we fix the url parse so it works, however, in my case it was the `PGX` driver

### How can we reproduce it (as minimally and precisely as possible)?

- Install Crowdsec
- Install and setup postgresql
```
postgres=# CREATE DATABASE crowdsec;
postgres=# CREATE USER crowdsec WITH PASSWORD 'NfWdKd#tqCD$yL632Rci';
postgres=# GRANT ALL PRIVILEGES ON DATABASE crowdsec TO crowdsec;
```
- Make a config.yaml.local with these contents
```
db_config:
  type: pgx
  user: crowdsec
  password: "NfWdKd#tqCD$yL632Rci"
  db_name: crowdsec
  host: 127.0.0.1
  port: 5432
```
- systemctl restart crowdsec
- crashed

### Crowdsec version

Not applicable
