### ISSUE TITLE
Statics target does not correctly set

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec#2325]
### What happened?

Cause of new Unmarshaled map, when you want to set a value on it using `target` it does not set correctly.

```yaml
onsuccess: next_stage
debug: true
name: crowdsecurity/laurel-logs
description: "Parse laurel json logs"
## 1.5.2 returns "" , 1.5.3 returns nil
filter: evt.Parsed.program == 'laurel' && UnmarshalJSON(evt.Parsed.message, evt.Unmarshaled, "auditd") in ["", nil]
statics:
  - meta: service
    value: laurel
  - target: evt.Unmarshaled.auditd.exe
    expression: evt.Unmarshaled.auditd.SYSCALL.exe
```

UnmarshlJSON runs correctly, however, the following target overwrite the `auditd` key with a string instead of setting `exe` on the map itself.

```
├ s01-parse
|       └ 🟢 crowdsecurity/laurel-logs (+2 ~1)
|               └ update evt.Stage : s01-parse -> s02-enrich
|               └ create evt.Unmarshaled.auditd : /usr/bin/tail
|               └ create evt.Meta.service : laurel
```

### What did you expect to happen?

For `target` to set `exe` on the `auditd` map instead of overwriting `auditd` map itself.

### How can we reproduce it (as minimally and precisely as possible)?

Walked through with @blotus he has some idea behind it.

### Crowdsec version

<details>

```console
$ cscli version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>
