### ISSUE TITLE
Profile notification filter

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec#2327]
### What would you like to be added?

Sometimes a user want to not send a notification because of certain machine ID or edge case. The current way to create a duplicate profile with the filter altered to pick up on the edge case. I purpose we create a `notification_filter` expression to purely filter this when it comes to notification rather than bloating by adding a duplicate profiles.

Current way:

<details>

```yaml
name: ignore_machine
#debug: true
filters:
 - Alert.Remediation == true && Alert.GetScope() == "Ip" && Alert.MachineID in ['XXXXX']
decisions:
 - type: ban
   duration: 4h
on_success: break
---
name: default_ip_remediation
#debug: true
filters:
 - Alert.Remediation == true && Alert.GetScope() == "Ip"
decisions:
 - type: ban
   duration: 4h
notifications:
  - slack_default  # Set the webhook in /etc/crowdsec/notifications/slack.yaml before enabling this.
on_success: break
```
</details>

Desired way:

<details>

```yaml
name: default_ip_remediation
filters:
 - Alert.Remediation == true && Alert.GetScope() == "Ip"
decisions:
 - type: ban
   duration: 4h
notification_filters:
  - Alert.MachineID not in ['XXXXX']
# Note it has to be inverted to return true when not in the array rather than previous way which needed to return true if it is in array
notifications:
  - slack_default  # Set the webhook in /etc/crowdsec/notifications/slack.yaml before enabling this.
on_success: break
```

</details>

/kind enhancement

### Why is this needed?

This will prevent users having complex profiles just for notifcation purposes when we can just create a filter for notifications

Currently users may like a single filter to enter the profile and creating 2 filters may cause complexity. However, in my eyes I do not see this as an issue as the user can do both but if they want to slim down the profile use the notification filter instead.
