### ISSUE TITLE
TLS handshake heartbeat

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec#2373]
### What happened?

Following [guide](https://www.crowdsec.net/blog/integrating-crowdsec-kubernetes-tls) results in heartbeat failing to handshake.

The only change I made for user report is updating the `image.tag: "dev"` here is a copy of my values
```
container_runtime: containerd
image:
  tag: "dev"
tls:
  enabled: true
  bouncer:
    reflector:
      namespaces: ["traefik"]
agent:
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Equal
      effect: NoSchedule
  # Specify each pod whose logs you want to process
  acquisition:
    # The namespace where the pod is located
    - namespace: traefik
      # The pod name
      podName: traefik-*
      # as in crowdsec configuration, we need to specify the program name to find a matching parser
      program: traefik
  env:
    - name: PARSERS
      value: "crowdsecurity/cri-logs"
    - name: COLLECTIONS
      value: "crowdsecurity/traefik"
    # When testing, allow bans on private networks
    - name: DISABLE_PARSERS
      value: "crowdsecurity/whitelists"
  persistentVolume:
    config:
      enabled: false
lapi:
  dashboard:
    enabled: false
    ingress:
      host: dashboard.local
      enabled: true
  persistentVolume:
    config:
      enabled: false
  env:
    # For an internal test, disable the Online API
    - name: DISABLE_ONLINE_API
      value: "true"
```

However, before doing this I didn't update the `image.tag` and still got the same error in `v1.4.5` so this issue is not new.

**Debugging: **

Forward 8080 to host

`kubectl port-forward -n crowdsec $(kubectl -n crowdsec get pods -l type=lapi -o jsonpath='{.items..metadata.name}') 8080:8080`

```
$ curl https://127.0.0.1:8080/health -vvv -k
*   Trying 127.0.0.1:8080...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: [NONE]
*  start date: Jul 24 09:33:46 2023 GMT
*  expire date: Oct 22 09:33:46 2023 GMT
*  issuer: CN=crowdsec-ca
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x5585b4026ad0)
> GET /health HTTP/2
> Host: 127.0.0.1:8080
> user-agent: curl/7.74.0
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 200
< cache-control: no-cache
< content-type: application/json; charset=utf-8
< expires: -1
< pragma: no-cache
< content-length: 15
< date: Mon, 24 Jul 2023 10:40:39 GMT
<
* Connection #0 to host 127.0.0.1 left intact
{"status":"up"}
```

```
2023/07/24 10:42:51 http: TLS handshake error from 10.244.1.1:53804: EOF
2023/07/24 10:43:01 http: TLS handshake error from 10.244.1.1:35202: EOF
2023/07/24 10:43:01 http: TLS handshake error from 10.244.1.1:35194: EOF
2023/07/24 10:43:11 http: TLS handshake error from 10.244.1.1:57084: EOF
2023/07/24 10:43:11 http: TLS handshake error from 10.244.1.1:57086: EOF
2023/07/24 10:43:21 http: TLS handshake error from 10.244.1.1:50656: EOF
2023/07/24 10:43:21 http: TLS handshake error from 10.244.1.1:50644: EOF
2023/07/24 10:43:31 http: TLS handshake error from 10.244.1.1:40914: EOF
2023/07/24 10:43:31 http: TLS handshake error from 10.244.1.1:40912: EOF
```

Port forward has an error if client sends more than 1 requests
```
Handling connection for 8080
Handling connection for 8080
E0724 10:49:06.132185   25918 portforward.go:394] error copying from local connection to remote stream: read tcp4 127.0.0.1:8080->127.0.0.1:59548: read: connection reset by peer
Handling connection for 8080
E0724 10:49:07.178247   25918 portforward.go:394] error copying from local connection to remote stream: read tcp4 127.0.0.1:8080->127.0.0.1:59592: read: connection reset by peer
```

 ^^ Note these errors do not show in LAPI logs ^^

### What did you expect to happen?

No common errors of EOF tls handshake

### How can we reproduce it (as minimally and precisely as possible)?

Stated above

### Crowdsec version

<details>

```console
$ cscli version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>
