### ISSUE TITLE
[container] X-Forwarded-For option

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec#2428]
### What would you like to be added?

Currently we allow the user to configure TLS options but if Security Engine is behind a reverse proxy to get the real IP of machine and bouncers user needs to configure the below options

```yaml title="config.yaml"
api:
  server:
    use_forwarded_for_headers: "<true|false>"
```

We should add the option to docker environment, however, it adds a bigger question of how we can support all options and not just a single one. 

/kind enhancement

### Why is this needed?

User can configure at environment level instead of mounting configuration to host for some edits.
