### ISSUE TITLE
Blacklist/Whitelist based on contry

### ISSUE THREAD

**Issue by karkazzul** [crowdsecurity/crowdsec#2680]
### What would you like to be added?

Completely new feature not currently available 

### Why is this needed?

Hello,

I have crowdsec installed with traefik in a docker environment and it works perfectly. However, I have a problem. As part of crowdsec, I created a whitelist corresponding to the public ip of our company. However, teleworking users access the protected service, but their public IP isn't fixed, so I can't include them in the whitelist. So I thought it would be nice to be able to create a whitelist or blacklist based on the country of origin of the IP address, especially as crowdsec already detects the country of the IP. I hope this feature will help others too. 

Have a nice day and happy holidays.

**Comment by LaurenceJJones** [comment]
Hi @karkazzul 

This is already achievable via creating a s02-enrich whitelist for example

```yaml
#/etc/crowdsec/parsers/s02-enrich/mywhitelist.yaml
name: karkazzul/countrylit
description: "Whitelist events from certain countries"
whitelist:
  reason: "whitelist countries"
  expression:
   - evt.Meta.IsoCode in ['AU']
```
