### ISSUE TITLE
API client gets stuck in infinite loop when sending invalid alerts

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#2687]
### What happened?

While debugging https://github.com/crowdsecurity/crowdsec/issues/2683 we managed to reproduce the bug and discover the issue: If the API client sends an alert that gets refused by LAPI (500), it will push it back to queue endlessly.

In this case, we triggered an alert (w/ **associated profile**) on an invalid range that LAPI refuses. [API client adds it back to queue of events to send, and retries forever, clogging the whole thing.](https://github.com/crowdsecurity/crowdsec/blob/master/cmd/crowdsec/output.go#L130)

### What did you expect to happen?

We should find a way to decide when to drop the event so we don't get stuck.

### How can we reproduce it (as minimally and precisely as possible)?

fake scenario:

```yaml
type: leaky
debug: true
name: xxx/http-bruteforce-login
description: "Detect advanced brute-force patterns on the login endpoint"
filter: " 1 == 1"
groupby: evt.Meta.SourceRange
capacity: 1
leakspeed: "1m"
blackhole: 10m
labels:
  service: http
  type: bruteforce
  remediation: true
scope:
  type: range
  expression: '""'
```

Profile:

```yaml
name: default_ip_remediation
#debug: true
filters:
 - Alert.Remediation == true && Alert.GetScope() == "Range"
decisions:
 - type: ban
   duration: 4h
#duration_expr: Sprintf('%dh', (GetDecisionsCount(Alert.GetValue()) + 1) * 4)
# notifications:
#   - slack_default  # Set the webhook in /etc/crowdsec/notifications/slack.yaml before enabling this.
#   - splunk_default # Set the splunk url and token in /etc/crowdsec/notifications/splunk.yaml before enabling this.
#   - http_default   # Set the required http parameters in /etc/crowdsec/notifications/http.yaml before enabling this.
#   - email_default  # Set the required email parameters in /etc/crowdsec/notifications/email.yaml before enabling this.
on_success: break
```

When the bucket overflows:

```
INFO[2023-12-27 10:28:04] (test/crowdsec) xx/http-bruteforce-login by range  : 4h ban on Range  
INFO[2023-12-27 10:28:04] CreateDecisionChunk: creating 1 decisions    
INFO[2023-12-27 10:28:04] 127.0.0.1 - [Wed, 27 Dec 2023 10:28:04 CET] "POST /v1/alerts HTTP/1.1 500 9.434689ms "crowdsec/v1.5.6-rc8-b6f272d0" " 
DEBU[2023-12-27 10:28:04] resp-jwt: 500                                
DEBU[2023-12-27 10:28:04] [headers] Content-Type : [application/json; charset=utf-8] 
DEBU[2023-12-27 10:28:04] [headers] Date : [Wed, 27 Dec 2023 09:28:04 GMT] 
DEBU[2023-12-27 10:28:04] [headers] Content-Length : [84]              
DEBU[2023-12-27 10:28:04] Response: HTTP/1.1 500 Internal Server Error
Content-Length: 84
Content-Type: application/json; charset=utf-8
Date: Wed, 27 Dec 2023 09:28:04 GMT

{"message":"machine 'test': creating alert decisions: : invalid ip address / range"} 
ERRO[2023-12-27 10:28:04] while pushing leftovers to api : failed sending alert to LAPI: API error: machine 'test': creating alert decisions: : invalid ip address / range 

```

And this will go on forever

### Crowdsec version

master

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>
