### ISSUE TITLE
[AppSec] Add real http request to hooks

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/crowdsec#2701]
### What would you like to be added?

I want to be able to access the http request from pre_eval, on_match etc. Currently we're exposing our own "ParsedHTTPRequest" that is not very convenient.

### Why is this needed?

A user may want to filter by a request variable for example I want to remove a rule by ID based on a subdomain I have

```yaml
pre_eval:
  - filter: "req.Host == 'mydomain.com'"
    apply:
      - RemoveInBandRuleByID(1234)
```
