### ISSUE TITLE
Appsec: crash when using `SendAlert()` with out of band rules

### ISSUE THREAD

**Issue by blotus** [crowdsecurity/crowdsec#2820]
With this configuration:
```
name: crowdsecurity/vpatch-test
default_remediation: ban
#log_level: debug
outband_rules:
 - crowdsecurity/base-config
 - crowdsecurity/vpatch-*
on_match:
 - filter: IsOutBand == true
   apply:
     - SendAlert()
     - CancelEvent()
```
When the appsec tries to send the events, it crashes because the event generation function will return nil as we have no in-band matches.

```
error : runtime error: invalid memory address or nil pointer dereference
version: v1.6.0-debian-pragmatic-amd64-4b8e6cd7
BuildDate: 2024-01-24_09:26:21
GoVersion: 1.21.3
goroutine 134 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
github.com/crowdsecurity/go-cs-lib/trace.WriteStackTrace({0x1dfd600, 0x35b33e0})
	github.com/crowdsecurity/go-cs-lib@v0.0.6/trace/trace.go:26 +0x245
github.com/crowdsecurity/go-cs-lib/trace.CatchPanic({0x210c1b5, 0x22})
	github.com/crowdsecurity/go-cs-lib@v0.0.6/trace/trace.go:41 +0xeb
panic({0x1dfd600?, 0x35b33e0?})
	runtime/panic.go:914 +0x21f
github.com/crowdsecurity/crowdsec/pkg/acquisition/modules/appsec.(*AppsecRunner).handleOutBandInterrupt(0xc000f1f080, 0xc0012006c0)
	github.com/crowdsecurity/crowdsec/pkg/acquisition/modules/appsec/appsec_runner.go:297 +0x486
github.com/crowdsecurity/crowdsec/pkg/acquisition/modules/appsec.(*AppsecRunner).handleRequest(0xc000f1f080, 0xc0012006c0)
	github.com/crowdsecurity/crowdsec/pkg/acquisition/modules/appsec/appsec_runner.go:356 +0x7e9
github.com/crowdsecurity/crowdsec/pkg/acquisition/modules/appsec.(*AppsecRunner).Run(0xc000f1f080, 0x367afa0)
	github.com/crowdsecurity/crowdsec/pkg/acquisition/modules/appsec/appsec_runner.go:373 +0x85
github.com/crowdsecurity/crowdsec/pkg/acquisition/modules/appsec.(*AppsecSource).StreamingAcquisition.func1.1()
	github.com/crowdsecurity/crowdsec/pkg/acquisition/modules/appsec/appsec.go:251 +0x3e
gopkg.in/tomb%2ev2.(*Tomb).run(0x367afa0, 0xc000d928c0?)
	gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:163 +0x2b
created by gopkg.in/tomb%2ev2.(*Tomb).Go in goroutine 133
	gopkg.in/tomb.v2@v2.0.0-20161208151619-d5d1b5820637/tomb.go:159 +0xe5
```
