### ISSUE TITLE
environment variable parsing in http plugin

### ISSUE THREAD

**Issue by fgeck** [crowdsecurity/crowdsec#2923]
### What would you like to be added?

/kind enhancement

I store my crowdsec configuration in a github respository.
For notifications I use http plugin to push data to my telegram bot, but the issue relates to any http plugin which pushes data using credentials to authenticate.

In the format section I can already use sprig `env` function to substitue env vars (see below).

To not be forced to store my credentials in the `notifications/http.yaml` file I would like to use environment variables in the http plugin which will be resolved.

Example:

```yaml
type: http # Don't change
name: http_default # Must match the registered plugin in the profile

# One of "trace", "debug", "info", "warn", "error", "off"
log_level: info

# group_wait: 30s # Time to wait collecting alerts before relaying a message to this plugin, eg "30s"
# group_threshold:    # Amount of alerts that triggers a message before <group_wait> has expired, eg "10"
# max_retry:          # Number of attempts to relay messages to plugins in case of error
# timeout:            # Time to wait for response from the plugin before considering the attempt a failure, eg "10s"

#-------------------------
# plugin-specific options

# The following template receives a list of models.Alert objects
# The output goes in the http request body

# Replace XXXXXXXXX with your Telegram chat ID
format: |
  {
   "chat_id": "{{ env "TELEGRAM_CHAT_ID" }}", 
   "text": "
     {{range . -}}  
     {{$alert := . -}}  
     {{range .Decisions -}}
     {{.Value}} will get {{.Type}} for next {{.Duration}} for triggering {{.Scenario}}.
     {{end -}}
     {{end -}}
   ",
   "reply_markup": {
      "inline_keyboard": [
          {{ $arrLength := len . -}}
          {{ range $i, $value := . -}}
          {{ $V := $value.Source.Value -}}
          [
              {
                  "text": "See {{ $V }} on shodan.io",
                  "url": "https://www.shodan.io/host/{{ $V -}}"
              },
              {
                  "text": "See {{ $V }} on crowdsec.net",
                  "url": "https://app.crowdsec.net/cti/{{ $V -}}"
              }
          ]{{if lt $i ( sub $arrLength 1) }},{{end }}
      {{end -}}
      ]
  }

url: https://api.telegram.org/{TELEGRAM_BOT_KEY}/sendMessage

method: POST
headers:
  Content-Type: "application/json"

```

### Why is this needed?

* Security improvement for users that store crowdsec configuration in a github repository as they can use environment variables to substitute credentials in their configuration yaml files
