### ISSUE TITLE
[Bug] Latest crowdsec image broken (v1.6.1): "downloading crowdsecurity/http-crawl-non_statics: invalid download hash"

### ISSUE THREAD

**Issue by ManiMatter** [crowdsecurity/crowdsec#2946]
### What happened?

Can't start latest crowdsec image (v1.6.1)

### What did you expect to happen?

That I can start it

### How can we reproduce it (as minimally and precisely as possible)?

I pull the image via docker-compose as follows. Starting it give me the error in below logs. 
V1.6.0 starts without problems.

```
 crowdsec:
   <<: *common-keys-core
   image: crowdsecurity/crowdsec:v1.6.1
   container_name: crowdsec
   environment:
     <<: *default-tz-puid-pgid   
     COLLECTIONS: "crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/iptables crowdsecurity/linux crowdsecurity/nginx crowdsecurity/sshd"
     GID: "${GID-1000}"
     CUSTOM_HOSTNAME: dSHB
   volumes:
     - /var/log:/var/log:ro
     - $DOCKERDIR/appdata/crowdsec/data:/var/lib/crowdsec/data
     - $DOCKERDIR/appdata/crowdsec/config:/etc/crowdsec
```

### Anything else we need to know?

Logs:
```
crowdsec  | Local agent already registered
crowdsec  | Check if lapi needs to register an additional agent
crowdsec  | sqlite database permissions updated
crowdsec  | Running: cscli  parsers install "crowdsecurity/docker-logs" 
crowdsec  | time="2024-04-18T12:59:53+02:00" level=info msg="Ignoring file /etc/crowdsec/parsers/s02-enrich/whitelists.yaml of type parsers"
crowdsec  | time="2024-04-18T12:59:53+02:00" level=info msg="Ignoring file /etc/crowdsec/hub/parsers/s02-enrich/crowdsecurity/whitelists.yaml of type parsers"
crowdsec  | time="2024-04-18T12:59:53+02:00" level=warning msg="crowdsecurity/docker-logs: overwrite"
crowdsec  | time="2024-04-18T12:59:53+02:00" level=info msg="Enabled crowdsecurity/docker-logs"
crowdsec  | time="2024-04-18T12:59:53+02:00" level=info msg="Run 'sudo systemctl reload crowdsec' for the new configuration to be effective."
crowdsec  | Running: cscli  parsers install "crowdsecurity/cri-logs" 
crowdsec  | time="2024-04-18T12:59:53+02:00" level=info msg="Ignoring file /etc/crowdsec/parsers/s02-enrich/whitelists.yaml of type parsers"
crowdsec  | time="2024-04-18T12:59:53+02:00" level=info msg="Ignoring file /etc/crowdsec/hub/parsers/s02-enrich/crowdsecurity/whitelists.yaml of type parsers"
crowdsec  | time="2024-04-18T12:59:53+02:00" level=warning msg="crowdsecurity/cri-logs: overwrite"
crowdsec  | time="2024-04-18T12:59:53+02:00" level=info msg="Enabled crowdsecurity/cri-logs"
crowdsec  | time="2024-04-18T12:59:53+02:00" level=info msg="Run 'sudo systemctl reload crowdsec' for the new configuration to be effective."
crowdsec  | Running: cscli  collections install "crowdsecurity/traefik" 
crowdsec  | time="2024-04-18T12:59:54+02:00" level=info msg="Ignoring file /etc/crowdsec/parsers/s02-enrich/whitelists.yaml of type parsers"
crowdsec  | time="2024-04-18T12:59:54+02:00" level=info msg="Ignoring file /etc/crowdsec/hub/parsers/s02-enrich/crowdsecurity/whitelists.yaml of type parsers"
crowdsec  | time="2024-04-18T12:59:54+02:00" level=warning msg="crowdsecurity/traefik-logs: overwrite"
crowdsec  | time="2024-04-18T12:59:54+02:00" level=warning msg="crowdsecurity/http-logs: overwrite"
crowdsec  | time="2024-04-18T12:59:54+02:00" level=error msg="Downloaded version doesn't match index, please 'hub update'"
crowdsec  | time="2024-04-18T12:59:54+02:00" level=fatal msg="error while installing 'crowdsecurity/traefik': while downloading crowdsecurity/http-crawl-non_statics: invalid download hash"
```

### Crowdsec version

v1.6.1

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>
