### ISSUE TITLE
Allow environment variables in parser and postoverflow config

### ISSUE THREAD

**Issue by ToshY** [crowdsecurity/crowdsec#3011]
### What would you like to be added?

/kind enhancement

### Why is this needed?

I've already mentioned this in a [Discord thread](https://discord.com/channels/921520481163673640/1234621284017504429), and after some reconsidering, I thought I would still like to have an enhancement where environment variables could be used in other config files as well.

---

Currently, the section regarding Notification plugins show that you can use environment variables in the config files (https://docs.crowdsec.net/docs/notification_plugins/intro#environment-variables). 

It would be nice to have this for other configs as well, like for parsers/postoverflows. An example would be using a parser to whilelist certain user IPs. 

`/etc/crowdsec/parsers/s02-enrich/user-whitelist.yaml`
```
name: crowdsecurity/user-whitelist
description: "Whitelist events from my ipv4 addresses"
filter: "1 == 1"
whitelist:
  reason: "My ipv4 ranges"
  ip: [${USER_IPV4_WHITELIST}]
  cidr:
    - "10.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
```

And where `${USER_IPV4_WHITELIST}` contains the following:

`.env`
```dotenv
USER_IPV4_WHITELIST="'12.34.56.78','10.11.12.13'"
```
