### ISSUE TITLE
Debian - Parser upgrade doesn't work

### ISSUE THREAD

**Issue by d0m84** [crowdsecurity/crowdsec#3147]
### What happened?

The parser crowdsecurity/dovecot-logs contains a bug in version 0.6 which was fixed in [0.8](https://app.crowdsec.net/hub/author/crowdsecurity/configurations/dovecot-logs)

CrowdSec is on Debian 12 using the Debian packages.

I tried to upgrade the parser with the following command but it doesn't work, it stays at version 0.6

```console
# cscli parsers upgrade crowdsecurity/dovecot-logs --force
INFO[23-07-2024 00:16:00] crowdsecurity/dovecot-logs : up-to-date
WARN[23-07-2024 00:16:00] crowdsecurity/dovecot-logs : overwrite
updated crowdsecurity/dovecot-logs
INFO[23-07-2024 00:16:00] 📦 crowdsecurity/dovecot-logs : updated
INFO[23-07-2024 00:16:00] Upgraded 1 items
INFO[23-07-2024 00:16:00] Run 'sudo systemctl reload crowdsec' for the new configuration to be effective.
```
```console
# cscli parsers list
PARSERS
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
 Name                             📦 Status   Version   Local Path
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
 crowdsecurity/apache2-logs       ✔️ enabled   1.3       /etc/crowdsec/parsers/s01-parse/apache2-logs.yaml
 crowdsecurity/dateparse-enrich   ✔️ enabled   0.2       /etc/crowdsec/parsers/s02-enrich/dateparse-enrich.yaml
 crowdsecurity/dovecot-logs       ✔️ enabled   0.6       /etc/crowdsec/parsers/s01-parse/dovecot-logs.yaml
 crowdsecurity/http-logs          ✔️ enabled   1.1       /etc/crowdsec/parsers/s02-enrich/http-logs.yaml
 crowdsecurity/nginx-logs         ✔️ enabled   1.3       /etc/crowdsec/parsers/s01-parse/nginx-logs.yaml
 crowdsecurity/postfix-logs       ✔️ enabled   0.4       /etc/crowdsec/parsers/s01-parse/postfix-logs.yaml
 crowdsecurity/postscreen-logs    ✔️ enabled   0.2       /etc/crowdsec/parsers/s01-parse/postscreen-logs.yaml
 crowdsecurity/sshd-logs          ✔️ enabled   2.0       /etc/crowdsec/parsers/s01-parse/sshd-logs.yaml
 crowdsecurity/syslog-logs        ✔️ enabled   0.8       /etc/crowdsec/parsers/s00-raw/syslog-logs.yaml
 crowdsecurity/whitelists         ✔️ enabled   0.2       /etc/crowdsec/parsers/s02-enrich/whitelists.yaml
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

### What did you expect to happen?

That the parser crowdsecurity/dovecot-logs gets upgraded to version 0.8

### How can we reproduce it (as minimally and precisely as possible)?

1. Install on Debian 12
2. cscli parsers install crowdsecurity/dovecot-logs
3. cscli parsers upgrade crowdsecurity/dovecot-logs --force

### Crowdsec version

<details>

```console
$ cscli version
2024/07/23 00:26:06 version: v1.4.6-6~deb12u1-debian
2024/07/23 00:26:06 Codename: alphaga
2024/07/23 00:26:06 BuildDate: 2023-07-15_09:29:33
2024/07/23 00:26:06 GoVersion: 1.19.8
2024/07/23 00:26:06 Platform: linux
2024/07/23 00:26:06 Constraint_parser: >= 1.0, <= 2.0
2024/07/23 00:26:06 Constraint_scenario: >= 1.0, < 3.0
2024/07/23 00:26:06 Constraint_api: v1
2024/07/23 00:26:06 Constraint_acquis: >= 1.0, < 2.0
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux s1 6.1.0-23-arm64 #1 SMP Debian 6.1.99-1 (2024-07-15) aarch64 GNU/Linux
```

</details>

**Comment by LaurenceJJones** [comment]
> ```
> crowdsecurity/dovecot-logs       ✔️ enabled   0.6       /etc/crowdsec/parsers/s01-parse/dovecot-logs.yaml
> ```

Can you provide your `config.yaml` and run `ls -la /etc/crowdsec/parsers/s01-parse/`

**Comment by d0m84** [comment]
Thanks for help.

My `/etc/crowdsec/config.yaml` is the distribution default:

<details>

```yaml
common:
  daemonize: true
  log_media: file
  log_level: info
  log_dir: /var/log/
  log_max_size: 20
  compress_logs: true
  log_max_files: 10
  working_dir: .
config_paths:
  config_dir: /etc/crowdsec/
  data_dir: /var/lib/crowdsec/data/
  simulation_path: /etc/crowdsec/simulation.yaml
  hub_dir: /var/lib/crowdsec/hub/
  index_path: /var/lib/crowdsec/hub/.index.json
  notification_dir: /etc/crowdsec/notifications/
  plugin_dir: /usr/lib/crowdsec/plugins/
crowdsec_service:
  acquisition_path: /etc/crowdsec/acquis.yaml
  acquisition_dir: /etc/crowdsec/acquis.d
  parser_routines: 1
cscli:
  output: human
  color: auto
db_config:
  log_level: info
  type: sqlite
  db_path: /var/lib/crowdsec/data/crowdsec.db
  #max_open_conns: 100
  #user:
  #password:
  #db_name:
  #host:
  #port:
  flush:
    max_items: 5000
    max_age: 7d
plugin_config:
  user: nobody # plugin process would be ran on behalf of this user
  group: nogroup # plugin process would be ran on behalf of this group
api:
  client:
    insecure_skip_verify: false
    credentials_path: /etc/crowdsec/local_api_credentials.yaml
  server:
    log_level: info
    listen_uri: 127.0.0.1:8080
    profiles_path: /etc/crowdsec/profiles.yaml
    console_path: /etc/crowdsec/console.yaml
    online_client: # Central API credentials (to push signals and receive bad IPs)
      credentials_path: /etc/crowdsec/online_api_credentials.yaml
    trusted_ips: # IP ranges, or IPs which can have admin API access
      - 127.0.0.1
      - ::1
#    tls:
#      cert_file: /etc/crowdsec/ssl/cert.pem
#      key_file: /etc/crowdsec/ssl/key.pem
prometheus:
  enabled: true
  level: full
  listen_addr: 127.0.0.1
  listen_port: 6060
```

</details>

```yaml
config_paths:
  hub_dir: /var/lib/crowdsec/hub/
```

The files are symlinks to the same folder so it looks like the issue is something else.


<details>

```console
# ls -la /etc/crowdsec/parsers/
total 20
drwxr-xr-x 5 root root 4096 Jul 22 19:58 .
drwxr-xr-x 7 root root 4096 Jul 22 21:18 ..
drwxr-xr-x 2 root root 4096 Jul 22 19:58 s00-raw
drwxr-xr-x 2 root root 4096 Jul 22 20:09 s01-parse
drwxr-xr-x 2 root root 4096 Jul 23 08:36 s02-enrich

# ls -la /etc/crowdsec/parsers/s01-parse/
total 32
drwxr-xr-x 2 root root 4096 Jul 22 20:09 .
drwxr-xr-x 5 root root 4096 Jul 22 19:58 ..
lrwxrwxrwx 1 root root   71 Jul 22 19:58 apache2-logs.yaml -> /var/lib/crowdsec/hub/parsers/s01-parse/crowdsecurity/apache2-logs.yaml
lrwxrwxrwx 1 root root   71 Jul 22 20:00 dovecot-logs.yaml -> /var/lib/crowdsec/hub/parsers/s01-parse/crowdsecurity/dovecot-logs.yaml
lrwxrwxrwx 1 root root   69 Jul 22 19:58 nginx-logs.yaml -> /var/lib/crowdsec/hub/parsers/s01-parse/crowdsecurity/nginx-logs.yaml
lrwxrwxrwx 1 root root   71 Jul 22 20:00 postfix-logs.yaml -> /var/lib/crowdsec/hub/parsers/s01-parse/crowdsecurity/postfix-logs.yaml
lrwxrwxrwx 1 root root   74 Jul 22 20:09 postscreen-logs.yaml -> /var/lib/crowdsec/hub/parsers/s01-parse/crowdsecurity/postscreen-logs.yaml
lrwxrwxrwx 1 root root   68 Jul 22 19:58 sshd-logs.yaml -> /var/lib/crowdsec/hub/parsers/s01-parse/crowdsecurity/sshd-logs.yaml
```

</details>

I understand that the CrowdSec repo contains the most recent software, I would like to use the Debian stable repo as I like their conservative approach for a release, which usually allows me to auto-update packages with no manual interaction.
