### ISSUE TITLE
docker local_api_credentials.yaml being re-created at startup

### ISSUE THREAD

**Issue by Kornelius777** [crowdsecurity/crowdsec#3437]
### What happened?

My machines run crowdsec in a [multi-server setup](https://docs.crowdsec.net/u/user_guides/multiserver_setup/).

Now, for the first time, I wanted to try a docker deployment.

The relevant part of my docker-compose.yml looks like:
```
  crowdsec:
    image: crowdsecurity/crowdsec
    hostname: crowdsec
    container_name: crowdsec
    environment: 
      COLLECTIONS: "crowdsecurity/nginx"
    depends_on:
      - nginx
    volumes:
      - /docker/crowdsec:/etc/crowdsec
      - /docker/logs-nginx:/var/log/nginx:ro
      - crowdsec-db:/var/lib/crowdsec/data/
      - /var/log/auth.log:/var/log/auth.log:ro
      - /var/log/syslog:/var/log/syslog.log:ro
```

After a first start, I issued 
`cscli lapi register --machine WHATEVER --url http://10.10.10.10:8080`

and on the LAPI:
`cscli machines validate WHATEVER`

Afterwards, /etc/crowdsec/local_api_credentials.yaml was pointing to the correct LAPI and the LAPI showed the new machine being online.

After a `docker compose down && docker compose up -d`, local_api_credentials.yaml was re-created from scratch with default values.

Well... This way, no multi-server setup is possible.

Please change this behaviour so that local_api_credentials.yaml will be preserved.

### What did you expect to happen?

Preserve local_api_credentials.yaml

### How can we reproduce it (as minimally and precisely as possible)?

see above

### Crowdsec version

docker crowdsecurity/crowdsec:latest

**Comment by Kornelius777** [comment]
answering myself:

My bad!

After amending my docker-compose.yml to
```
  crowdsec:
    image: crowdsecurity/crowdsec
    hostname: crowdsec
    container_name: crowdsec
    environment: 
      COLLECTIONS: "crowdsecurity/nginx"
      DISABLE_LOCAL_API: true
      AGENT_USERNAME: "WHATEVER"
      AGENT_PASSWORD: "WHATEVER"
      LOCAL_API_URL: "http://10.10.10.10:8080"
    depends_on:
      - nginx
    volumes:
      - /docker/crowdsec:/etc/crowdsec
      - /docker/logs-nginx:/var/log/nginx:ro
      - crowdsec-db:/var/lib/crowdsec/data/
      - /var/log/auth.log:/var/log/auth.log:ro
      - /var/log/syslog:/var/log/syslog.log:ro
```
everything works as expected.

Please close!
