### ISSUE TITLE
[appsec] `log_level` for appsec-configs loading native modsec rules is ignored

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#3439]
### What happened?

Having something like:

```yaml
name: smth/rules
log_level: trace
default_remediation: ban
inband_rules:
 - smth/rules
```

With `smth/rules` being:

```yaml
name: smth/rules
seclang_rules:
 - SecRuleEngine On
 - SecRequestBodyAccess On
seclang_files_rules:
  - some-native-modsec.rules 
```

the `log_level` directive seems to be ignored as I don't get info about the loading or processing of native modsec rules.

### What did you expect to happen?

do not ignore `log_level`

### How can we reproduce it (as minimally and precisely as possible)?

see sample config above

### Crowdsec version

<details>

```console
$ cscli version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw
# paste output here
```

</details>

### Acquisition config

<details>
```console
# On Linux:
$ cat /etc/crowdsec/acquis.yaml /etc/crowdsec/acquis.d/*
# paste output here

# On Windows:
C:\> Get-Content C:\ProgramData\CrowdSec\config\acquis.yaml
# paste output here
</details>


### Config show

<details>

```console
$ cscli config show
# paste output here
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

</details>
