### ISSUE TITLE
acquis.yaml is a folder in docker image

### ISSUE THREAD

**Issue by Talanor** [crowdsecurity/crowdsec#3480]
### What happened?

Following the Traefik quickstart guide (with docker) : https://docs.crowdsec.net/docs/next/appsec/quickstart/traefik/
it links to the "Getting started", so taking the docker doc : https://docs.crowdsec.net/u/getting_started/installation/docker

I was testing what I thought would be the bare bones of a docker-compose.yml to start : 
```
services:
  crowdsec:
    image: crowdsecurity/crowdsec:v1.6.5
    restart: unless-stopped
    environment:
      COLLECTIONS: "crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules"
      GID: "${GID-1000}"
    volumes:
      # - ./data/crowdsec/acquis.d:/etc/crowdsec/acquis.d
      - ./data/crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - ./data/crowdsec-db:/var/lib/crowdsec/data/
      - ./data/crowdsec-config:/etc/crowdsec/
```

with an empty ./data/crowdsec/acquis.yaml : 
```
$ cat ./data/crowdsec/acquis.yaml 
$ ls -la ./data/crowdsec/acquis.yaml
-rw-r--r-- 1 root root 0 Feb 23 02:59 ./data/crowdsec/acquis.yaml
```

When I `docker compose up`, I get : 
```
$ docker compose up
Attaching to crowdsec-1
Gracefully stopping... (press Ctrl+C again to force)
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "XXXX/crowdsec/data/crowdsec/acquis.yaml" to rootfs at "/etc/crowdsec/acquis.yaml": mount src=XXXX/crowdsec/data/crowdsec/acquis.yaml, dst=/etc/crowdsec/acquis.yaml, dstFd=/proc/thread-self/fd/8, flags=0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
exit status 1
```

When I remove the mount : 
```
services:
  crowdsec:
    image: crowdsecurity/crowdsec:v1.6.5
    restart: unless-stopped
    environment:
      COLLECTIONS: "crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules"
      GID: "${GID-1000}"
    volumes:
      # - ./data/crowdsec/acquis.d:/etc/crowdsec/acquis.d
      # - ./data/crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - ./data/crowdsec-db:/var/lib/crowdsec/data/
      - ./data/crowdsec-config:/etc/crowdsec/
```

and `docker compose up`, the container spawns but yields : 
```
crowdsec-1  | time="2025-02-23T06:33:02Z" level=info msg="loading acquisition file : /etc/crowdsec/acquis.yaml"
crowdsec-1  | time="2025-02-23T06:33:02Z" level=fatal msg="crowdsec init: while loading acquisition config: failed to read /etc/crowdsec/acquis.yaml: read /etc/crowdsec/acquis.yaml: is a directory"
crowdsec-1 exited with code 0
```

### What did you expect to happen?

For `/etc/crowdsec/acquis.yaml` not to be a directory

### How can we reproduce it (as minimally and precisely as possible)?

Detailed above

### Crowdsec version

<details>
1.6.5
</details>
According to the compose file

### OS version

<details>

```console
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux dmz-web-host 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux

```

</details>

### Acquisition config

<details>
Empty
</details>
