### ISSUE TITLE
send http notification, decisions is null but test is ok

### ISSUE THREAD

**Issue by qianlongzt** [crowdsecurity/crowdsec#3686]
### What happened?

```
time="2025-06-13T15:38:04Z" level=debug msg="making HTTP POST call to https://api.telegram.org/bot<redacted >/sendMessage with body {\n\"chat_id\": \"redacted\", \n\"text\": \"\n  \",\n\"reply_markup\": {\n    \"inline_keyboard\": [\n        [\n            {\n                \"text\": \"See 104.244.77.50 on shodan.io\",\n                \"url\": \"https://www.shodan.io/host/104.244.77.50\"\n            },\n            {\n                \"text\": \"See 104.244.77.50 on crowdsec.net\",\n                \"url\": \"https://app.crowdsec.net/cti/104.244.77.50\"\n            }\n        ]\n    ]\n}\n" @module=http-plugin
time="2025-06-13T15:38:05Z" level=debug msg="got response {\"ok\":false,\"error_code\":400,\"description\":\"Bad Request: text must be non-empty\"}" @module=http-plugin
```
```
root@crowdsec-lapi-598d45f8d8-j28g7:/# cscli notification test http_default
INFO Prepending yaml: '/etc/crowdsec/profiles.yaml' with '/etc/crowdsec/profiles.yaml.local'
DEBU[0000] starting plugin                               args="[/usr/local/lib/crowdsec/plugins/notification-http]" path=/usr/local/lib/crowdsec/plugins/notification-http
DEBU[0000] plugin started                                path=/usr/local/lib/crowdsec/plugins/notification-http pid=285
DEBU[0000] waiting for RPC address                       path=/usr/local/lib/crowdsec/plugins/notification-http
DEBU[0000] using plugin                                  version=1
TRAC[0000] waiting for stdio data
INFO registered plugin http_default
INFO pluginTomb dying
INFO[0000] received signal for http_default config       @module=http-plugin
INFO killing all plugins
DEBU[0001] received EOF, stopping recv loop              err="rpc error: code = Unavailable desc = error reading from server: EOF"
INFO[0001] plugin process exited                         path=/usr/local/lib/crowdsec/plugins/notification-http pid=285
DEBU[0001] plugin exited
```

### What did you expect to happen?

decisions is not null when send notification

### How can we reproduce it (as minimally and precisely as possible)?

create telegram notification
https://docs.crowdsec.net/docs/next/local_api/notification_plugins/telegram

### Anything else we need to know?

decisions is null
```json
[{"capacity":5,"decisions":null,"events":[{"meta":[{"key":"ASNNumber","value":"0"},{"key":"IsInEU","value":"false"},{"key":"datasource_path","value":"journalctl-%!s(MISSING)-D./var/log/journal._SYSTEMD_UNIT=ssh.service"},{"key":"datasource_type","value":"journalctl"},{"key":"log_type","value":"ssh_failed-auth"},{"key":"machine","value":"al-sh-4"},{"key":"service","value":"ssh"},{"key":"source_ip","value":"100.100.1.119"},{"key":"target_user","value":"raoot"},{"key":"timestamp","value":"2025-06-13T16:22:28Z"}],"timestamp":"2025-06-13T16:22:28Z"},{"meta":[{"key":"ASNNumber","value":"0"},{"key":"IsInEU","value":"false"},{"key":"datasource_path","value":"journalctl-%!s(MISSING)-D./var/log/journal._SYSTEMD_UNIT=ssh.service"},{"key":"datasource_type","value":"journalctl"},{"key":"log_type","value":"ssh_failed-auth"},{"key":"machine","value":"al-sh-4"},{"key":"service","value":"ssh"},{"key":"source_ip","value":"100.100.1.119"},{"key":"target_user","value":"raoot"},{"key":"timestamp","value":"2025-06-13T16:22:28Z"}],"timestamp":"2025-06-13T16:22:28Z"},{"meta":[{"key":"ASNNumber","value":"0"},{"key":"IsInEU","value":"false"},{"key":"datasource_path","value":"journalctl-%!s(MISSING)-D./var/log/journal._SYSTEMD_UNIT=ssh.service"},{"key":"datasource_type","value":"journalctl"},{"key":"log_type","value":"ssh_failed-auth"},{"key":"machine","value":"al-sh-4"},{"key":"service","value":"ssh"},{"key":"source_ip","value":"100.100.1.119"},{"key":"target_user","value":"raoot"},{"key":"timestamp","value":"2025-06-13T16:22:33Z"}],"timestamp":"2025-06-13T16:22:33Z"},{"meta":[{"key":"ASNNumber","value":"0"},{"key":"IsInEU","value":"false"},{"key":"datasource_path","value":"journalctl-%!s(MISSING)-D./var/log/journal._SYSTEMD_UNIT=ssh.service"},{"key":"datasource_type","value":"journalctl"},{"key":"log_type","value":"ssh_failed-auth"},{"key":"machine","value":"al-sh-4"},{"key":"service","value":"ssh"},{"key":"source_ip","value":"100.100.1.119"},{"key":"target_user","value":"raoot"},{"key":"timestamp","value":"2025-06-13T16:22:33Z"}],"timestamp":"2025-06-13T16:22:33Z"},{"meta":[{"key":"ASNNumber","value":"0"},{"key":"IsInEU","value":"false"},{"key":"datasource_path","value":"journalctl-%!s(MISSING)-D./var/log/journal._SYSTEMD_UNIT=ssh.service"},{"key":"datasource_type","value":"journalctl"},{"key":"log_type","value":"ssh_failed-auth"},{"key":"machine","value":"al-sh-4"},{"key":"service","value":"ssh"},{"key":"source_ip","value":"100.100.1.119"},{"key":"target_user","value":"raoot"},{"key":"timestamp","value":"2025-06-13T16:22:35Z"}],"timestamp":"2025-06-13T16:22:35Z"},{"meta":[{"key":"ASNNumber","value":"0"},{"key":"IsInEU","value":"false"},{"key":"datasource_path","value":"journalctl-%!s(MISSING)-D./var/log/journal._SYSTEMD_UNIT=ssh.service"},{"key":"datasource_type","value":"journalctl"},{"key":"log_type","value":"ssh_failed-auth"},{"key":"machine","value":"al-sh-4"},{"key":"service","value":"ssh"},{"key":"source_ip","value":"100.100.1.119"},{"key":"target_user","value":"raoot"},{"key":"timestamp","value":"2025-06-13T16:22:36Z"}],"timestamp":"2025-06-13T16:22:36Z"}],"events_count":6,"labels":null,"leakspeed":"10s","machine_id":"crowdsec-agent-v7hsm","message":"Ip 100.100.1.119 performed 'crowdsecurity/ssh-bf' (6 events over 7.249862315s) at 2025-06-13 16:22:36.281909174 +0000 UTC","meta":[{"key":"target_user","value":"[\"raoot\"]"}],"remediation":true,"scenario":"crowdsecurity/ssh-bf","scenario_hash":"242f36684d66bbae3044e576b7cfffef62d5323465f3f74f87923167c6d93356","scenario_version":"0.3","simulated":false,"source":{"as_number":"0","ip":"100.100.1.119","scope":"Ip","value":"100.100.1.119"},"start_at":"2025-06-13T16:22:29.032047169Z","stop_at":"2025-06-13T16:22:36.281909484Z","uuid":"5f9b261c-d05e-4b01-a3ef-9ebc26e75767"}]
```

![Image](https://github.com/user-attachments/assets/7680171e-8a51-4939-a77a-ac04bab92aa7)

### Crowdsec version

<details>

```console
$ cscli version

version: v1.6.8-f209766e
Codename: alphaga
BuildDate: 2025-03-25_15:53:20
GoVersion: 1.24.1
Platform: docker
libre2: C++
User-Agent: crowdsec/v1.6.8-f209766e-docker
Constraint_parser: >= 1.0, <= 3.0
Constraint_scenario: >= 1.0, <= 3.0
Constraint_api: v1
Constraint_acquis: >= 1.0, < 2.0
Built-in optional components: cscli_setup, datasource_appsec, datasource_cloudwatch, datasource_docker, datasource_file, datasource_http, datasource_journalctl, datasource_k8s-audit, datasource_kafka, datasource_kinesis, datasource_loki, datasource_s3, datasource_syslog, datasource_victorialogs, datasource_wineventlog
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a

Linux crowdsec-lapi-779454997d-8lshq 6.14.0-15-generic #15-Ubuntu SMP PREEMPT_DYNAMIC Sun Apr  6 15:05:05 UTC 2025 x86_64 GNU/Linux
```

</details>

### Enabled collections and parsers

<details>

```console
$ cscli hub list -o raw

Loaded: 141 parsers, 10 postoverflows, 761 scenarios, 8 contexts, 4 appsec-configs, 115 appsec-rules, 139 collections
name,status,version,description,type
crowdsecurity/cri-logs,enabled,0.1,CRI logging format parser,parsers
crowdsecurity/dateparse-enrich,enabled,0.2,,parsers
crowdsecurity/docker-logs,enabled,0.1,docker json logs parser,parsers
crowdsecurity/geoip-enrich,enabled,0.5,"Populate event with geoloc info : as, country, coords, source range.",parsers
crowdsecurity/sshd-logs,enabled,3.0,Parse openSSH logs,parsers
crowdsecurity/syslog-logs,enabled,0.8,,parsers
crowdsecurity/whitelists,enabled,0.3,Whitelist events from private ipv4 addresses,parsers
crowdsecurity/ssh-bf,enabled,0.3,Detect ssh bruteforce,scenarios
crowdsecurity/ssh-cve-2024-6387,enabled,0.2,Detect exploitation attempt of CVE-2024-6387,scenarios
crowdsecurity/ssh-refused-conn,enabled,0.1,Detect sshd refused connections,scenarios
crowdsecurity/ssh-slow-bf,enabled,0.4,Detect slow ssh bruteforce,scenarios
crowdsecurity/bf_base,enabled,0.1,,contexts
crowdsecurity/linux,enabled,0.2,core linux support : syslog+geoip+ssh,collections
crowdsecurity/sshd,enabled,0.6,sshd support : parser and brute-force detection,collections
```

</details>

### Acquisition config

<details>

```console
filenames:
  - /var/log/containers/traefik-*_traefik_*.log
force_inotify: true
poll_without_inotify: true
labels:
  type: containerd
  program: traefik
---
filenames:
  - /var/log/containers/vaultwarden-*_default_vaultwarden-*.log
force_inotify: true
poll_without_inotify: true
labels:
  type: containerd
  program: Vaultwarden
---
source: journalctl
journalctl_filter:
  - "-D"
  - "/var/log/journal"
  - "_SYSTEMD_UNIT=ssh.service"
labels:
  type: syslog

</details>


### Config show

<details>

```console
$ cscli config show
Global:
   - Configuration Folder   : /etc/crowdsec
   - Data Folder            : /var/lib/crowdsec/data
   - Hub Folder             : /etc/crowdsec/hub
   - Simulation File        : /etc/crowdsec/simulation.yaml
   - Log Folder             : /var/log
   - Log level              : info
   - Log Media              : stdout
Crowdsec:
  - Acquisition File        : /etc/crowdsec/acquis.yaml
  - Parsers routines        : 1
  - Acquisition Folder      : /etc/crowdsec/acquis.d
cscli:
  - Output                  : human
  - Hub Branch              :
API Client:
  - URL                     : http://localhost:8080/
  - Login                   : crowdsec-lapi-779454997d-8lshq
  - Credentials File        : /etc/crowdsec/local_api_credentials.yaml
Local API Server:
  - Listen URL              : 0.0.0.0:8080
  - Listen Socket           :
  - Profile File            : /etc/crowdsec/profiles.yaml

  - Trusted IPs:
      - 127.0.0.1
      - ::1
  - Database:
      - Type                : sqlite
      - Path                : /var/lib/crowdsec/data/crowdsec.db
      - Flush age           : 7d
      - Flush size          : 5000
```

</details>

### Prometheus metrics

<details>

```console
$ cscli metrics
# paste output here
```

</details>

### Related custom configs versions (if applicable) : notification plugins, custom scenarios, parsers etc.

<details>

/etc/crowdsec/profiles.yaml.local
```yaml
name: notifications
debug: true
filters:
- Alert.Remediation == true && Alert.GetScope() == "Ip"
# decisions:
# - type: ban
#   duration: 4h
#duration_expr: "Sprintf('%dh', (GetDecisionsCount(Alert.GetValue()) + 1) * 4)"
notifications:
  - http_default
on_success: continue
```

/etc/crowdsec/notifications/http.yaml
```yaml

type: http          # Don't change
name: http_default  # Must match the registered plugin in the profile

# One of "trace", "debug", "info", "warn", "error", "off"
log_level: debug

# group_wait:         # Time to wait collecting alerts before relaying a message to this plugin, eg "30s"
# group_threshold:    # Amount of alerts that triggers a message before <group_wait> has expired, eg "10"
# max_retry:          # Number of attempts to relay messages to plugins in case of error
# timeout:            # Time to wait for response from the plugin before considering the attempt a failure, eg "10s"

#-------------------------
# plugin-specific options

# The following template receives a list of models.Alert objects
# The output goes in the http request body

format: |
  {
  "chat_id": "{{env "TG_CHAT_ID" }}",
  "text": " {{ .| toJson }}
    {{range . -}}
      {{$alert := . -}}
      {{range .Decisions -}}
        {{.Value}} will get {{.Type}} for next {{.Duration}} for triggering {{.Scenario}}.
      {{end -}}
    {{end -}}
  ",
  "reply_markup": {
      "inline_keyboard": [
          {{ $arrLength := len . -}}
          {{ range $i, $value := . -}}
          {{ $V := $value.Source.Value -}}
          [
              {
                  "text": "See {{ $V }} on shodan.io",
                  "url": "https://www.shodan.io/host/{{ $V -}}"
              },
              {
                  "text": "See {{ $V }} on crowdsec.net",
                  "url": "https://app.crowdsec.net/cti/{{ $V -}}"
              }
          ]{{if lt $i ( sub $arrLength 1) }},{{end }}
      {{end -}}
      ]
  }

url: https://api.telegram.org/bot${TG_TOKEN}/sendMessage

method: POST
headers:
  Content-Type: "application/json"
```

</details>
