### ISSUE TITLE
Bug/capi : cscli capi status fails to authenticate on the central API

### ISSUE THREAD

**Issue by dani** [crowdsecurity/crowdsec#623]
**Describe the bug**
Installed crowdsec manually, with --bininstall. Then registered on the central API as explained in the doc with
```
cscli capi register
```
/etc/crowdsec/online_api_credentials.yaml was created successfuly and contains what looks like valid credentials. I've restarted crowdsec, but trying to get the status of the central API fails
```
[root@el8 ~]# cscli --debug capi status
DEBU[0000] Using /etc/crowdsec/config.yaml as configuration file 
DEBU[0000] loading hub idx /etc/crowdsec/hub/.index.json 
DEBU[0000] 4 item types in hub index                    
DEBU[0000] scanning /etc/crowdsec                       
DEBU[0000] scanning /etc/crowdsec/hub                   
INFO[0000] Loaded credentials from /etc/crowdsec/online_api_credentials.yaml 
INFO[0000] Trying to authenticate with username 6ad632a99f9542fab2f3776bfd557175FFmoTEfxLtizQRrT on https://api.crowdsec.net/ 
FATA[0000] Failed to authenticate to Central API (CAPI) : API error: Invalid request body ([instance type (null) does not match any allowed primitive type (allowed: ["array"])]) 
[root@el8 ~]# 
```
api.server in config.yaml is
```
  server:
    log_level: info
    listen_uri: 0.0.0.0:8080
    profiles_path: /etc/crowdsec/profiles.yaml
    online_client:
      credentials_path: /etc/crowdsec/online_api_credentials.yaml
```

**Expected behavior**
cscli cpi status should suceed

**Technical Information (please complete the following information):**
 - OS: CentOS Stream 8
 - Version v1.0.7

**Additional context**
Add any other context about the problem here, for example `/var/log/crowdsec.log` or error messages.
