### ISSUE TITLE
Improvement/crowdsec : provide some kind of variable support

### ISSUE THREAD

**Issue by dani** [crowdsecurity/crowdsec#655]
when installing parsers and decisions from the hub, all values (especially buckets capacity and leakspeed) are "hardcoded". It'd be great to have some kind of variable support so I could override those values locally, without having to fork the entire scenario from the hub.

Eg
```
type: leaky
name: crowdsecurity/postfix-spam
description: "Detect spammers"
variables:
  # Provide default values
  postfix_leekspeed: 10s
  postfix_capacity: 5
filter: "evt.Meta.log_type_enh == 'spam-attempt' || evt.Meta.log_type == 'postfix' && evt.Meta.action == 'reject'"
leakspeed: $postfix_leakspeed
references:
  - https://en.wikipedia.org/wiki/Spamming
capacity: $postfix_capacity
groupby: evt.Meta.source_ip
blackhole: 1m
[...]
```

Then in eg /etc/crowdsec/variables.yml, I could override those with
```
postfix_leakspeed: 120s
postfix_capacity: 3
```
And those values would take precedence over the variables set in the scenario.
