### ISSUE TITLE
Improvement/specify database settings with docker env instead of messing arround in config.yaml

### ISSUE THREAD

**Issue by rafipiccolo** [crowdsecurity/crowdsec#722]
I would like to specify mysql settings with docker env instead of writing it in the config.yaml

usually when using docker you provide secrets with env variables.
that way we dont need to extract config files from the container. And then we dont need to verify that they are up to date when the new version of the config file is released.

I think it would only require few lines of code here to read the env variables and write it in the appropriate line in config.yaml before booting crowsec
https://github.com/crowdsecurity/crowdsec/blob/6f8b6cdb4293bd04169e5ff2c68d54309e735d9c/docker/docker_start.sh

i usually use this variables on my personal projects :
MYSQL=mysql://user:password@host/database?charset=utf8mb4

but i would also like something like this to ease parsing
MYSQL_USER=user
MYSQL_PASSWORD=password
MYSQL_HOST=host
MYSQL_DB=database

Is this good for you ?

**Comment by he2ss** [comment]
Hi @rafipiccolo,

Thanks for your suggestion. 
I think we should as a first step make variables for this configuration part :
```yaml
db_config:
  log_level: info
  type: sqlite
  db_path: /var/lib/crowdsec/data/crowdsec.db
  #user: 
  #password:
  #db_name:
  #host:
  #port:
  flush:
    max_items: 5000
    max_age: 7d
```
It will be something like : 
```
DB_LOG_LEVEL=
DB_TYPE=
DB_PATH=
DB_USER=
DB_PASSWORD=
DB_HOST=
DB_PORT=
DB_FLUSH_MAX_ITEMS=
DB_FLUSH_MAX_AGE=
```
Those variables will overwrite the config file if both variables and config file are specified.

**Comment by he2ss** [comment]
Hi again @rafipiccolo,

Forgot an existing feature, but your can already set variables : 
https://doc.crowdsec.net/Crowdsec/v1/references/crowdsec-config/#environment-variable.
No need to improve the docker_start script.

**Comment by rafipiccolo** [comment]
Thanks, its perfect !
It's working using following config.
Could this be the default config.yaml so that people dont need to edit the config when using docker ?

(https://github.com/crowdsecurity/crowdsec/blob/master/docker/config.yaml)
config.yaml
```
db_config:
  log_level: info
  type: ${DB_TYPE}
  db_path: /var/lib/crowdsec/data/crowdsec.db
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  db_name: ${DB_NAME}
  host: ${DB_HOST}
  port: ${DB_PORT}
  flush:
    max_items: 5000
    max_age: 7d
```

i added compose for reference

docker-compose.yml
```
crowdsec:
        container_name: crowdsec
        restart: always
        image: crowdsecurity/crowdsec:latest
        volumes:
            - ./crowdsec/config/config.yaml:/etc/crowdsec/config.yaml
            - ./crowdsec/config/acquis.yaml:/etc/crowdsec/acquis.yaml
            - ./crowdsec/config/local_api_credentials.yaml:/etc/crowdsec/local_api_credentials.yaml
            - ./crowdsec/config/online_api_credentials.yaml:/etc/crowdsec/online_api_credentials.yaml
            - /var/log/auth.log:/logs/auth.log:ro
            - /var/log/syslog:/logs/syslog:ro
        environment:
            - "DB_TYPE=mysql"
            - "DB_USER=root"
            - "DB_PASSWORD=xxx"
            - "DB_NAME=crowdsec"
            - "DB_HOST=mysql"
            - "DB_PORT=3306"
            - "COLLECTIONS=crowdsecurity/sshd"
```
