### ISSUE TITLE
Bug/ unable to create alerts: event timestamp '' : parsing time \"\" as \"2006-01-02T15:04:05Z07:00\"

### ISSUE THREAD

**Issue by FidoUser** [crowdsecurity/crowdsec#736]
Please, start your issue name (after `Bug`) with the component name impacted by this feature request and a small description of the Bug. Example: `Bug/cscli: issue with ....` and remove this line :)

**Describe the bug**
My custom decisions periodically can not work as expected
In log
```
time="06-04-2021 17:44:18" level=info msg="(3d61908636144fe39e836ccb745a58adsve5wWrxFJQ4udV6/crowdsec) crowdsecurity/asterisk-bf by ip 10.9.78.97 : 4h ban on Ip 10.9.78.97"
time="06-04-2021 17:44:18" level=error msg="while pushing to api : failed sending alert to LAPI: API error: unable to create alerts: event timestamp '' : parsing time \"\" as \"2006-01-02T15:04:05Z07:00\": cannot parse \"\" as \"2006\": unable to parse time"
```
These events add to logfile until restart crowdsec
 

**To Reproduce**
Application log event like this
`[2021-04-06 17:17:49] NOTICE[911] chan_sip.c: Registration from '<sip:12313@10.9.99.9>' failed for '10.9.78.97:51076' - Wrong password`

Parser:

```
onsuccess: next_stage
filter: "evt.Parsed.program == 'asterisk'"
name: crowdsecurity/asterisk-logs
description: "Parse Asterisk full logs"
nodes:
  - grok:
      pattern: Registration from '<%{WORD:protocol}:%{WORD:login}@%{IP:ast_IP}>' failed for '%{IP:source_ip}:[0-9]+' - (Wrong password|Username/auth name mismatch)
      apply_on: message
      statics:
        - meta: target_user
          expression: "evt.Parsed.login"
        - meta: source_ip
          expression: "evt.Parsed.source_ip"

statics:
    - meta: log_type
      value: asterisk_failed-auth
```

**Expected behavior**
timestamp can use current  time and decisions will add IP

**Screenshots**

**Technical Information (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-65-generic x86_64)
 - Version v1.0.9-4-debian

**Comment by FidoUser** [comment]
Issue reproduce with this **scenario**

```
type: leaky

name: crowdsecurity/asterisk-bf
description: "Detect asterisk bruteforce"
filter: "evt.Meta.log_type == 'asterisk_failed-auth'"
leakspeed: "10s"
capacity: 5
groupby: evt.Meta.source_ip
blackhole: 1m
reprocess: true
cache_size: 2
labels:
 service: asterisk
 type: bruteforce
 remediation: true  #for ban IP
```

If use **blackhole: 5m** issue not occurred

**Comment by buixor** [comment]
Hello @FidoUser !

Yes, this is a poor documentation issue on our side : For everything to go smoothly, crowdsec expects a timestamp (extracted from the log) to be present in `evt.StrTime`. If your logs are parsed by syslog it's already been taken care of, but if your daemon logs directly, you should take care of this, for example by adding this to your parser :

```yaml
onsuccess: next_stage
filter: "evt.Parsed.program == 'asterisk'"
name: crowdsecurity/asterisk-logs
description: "Parse Asterisk full logs"
nodes:
#notice we're capturing timestamp here
  - grok:
      pattern: \[%{GREEDYDATA:date}\] %{WORD}\[%{NUMBER:pid}\] chan_sip.c: Registration from '<%{WORD:protocol}:%{WORD:login}@%{IP:ast_IP}>' failed for '%{IP:source_ip}:[0-9]+' - (Wrong password|Username/auth name mismatch)
      apply_on: message
      statics:
        - meta: target_user
          expression: "evt.Parsed.login"
        - meta: source_ip
          expression: "evt.Parsed.source_ip"
statics:
    - meta: log_type
      value: asterisk_failed-auth
#notice time tracking here
    - target: evt.StrTime
      expression: evt.Parsed.date
```

This should help solve the issue for now.

In the meanwhile, I'm updating the documentation and opening an issue so that we don't block alerts without timestamps.

**Comment by FidoUser** [comment]
Thank you for explanation

If logs does not contain time in any format, how to populate **evt.StrTime**  with current time on crowdsec server. For example how to set this evt.StrTime in **statics** ?

**Comment by buixor** [comment]
Hello, sorry for the delay.

Right now, you could set it to a static string :

```yaml
statics:
 - target: evt.StrTime
   value: "2006/01/02 15:04"
```

Beware, it might have some unintended consequences ... 

I think add a `expr` helper to allow you to set it to `now()` from statics (like those defined in https://github.com/crowdsecurity/crowdsec/blob/master/pkg/exprhelpers/exprlib.go), would do the trick and would be preferable.

Out of curiosity, why would you want not to extract the timestamp from logs ?
