### ISSUE TITLE
Improvement/cscli: add versioning for local parsers/post-overflows/etc.

### ISSUE THREAD

**Issue by Lamera** [crowdsecurity/crowdsec#777]
**Is your feature request related to a problem? Please describe.**
At this time our custom whitelist config is not versioned. This can be an issue when you have multiple instances and you made changes to this config. Then you never can be sure, which version this file is. I tried to add a version number in the config file, but then crowdsec doesn't start anymore.

**Describe the solution you'd like**
In `cscli hub list` local files should also have a version number. The configuration file, for example my_whitelist.yaml should have an option to define a version number in the yaml file. 

**Example of what you imagine**
```
name: me/whitelists
description: "Whitelist events from private ipv4 addresses"
version: 1.2
whitelist:
  reason: "private ipv4 ranges"
  ip:
    - "127.0.0.1"
```
