### ISSUE TITLE
Improvement/Allow grok patterns to run on `expr` result

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/crowdsec#822]
**Is your feature request related to a problem? Please describe.**

While dealing with some uncommon log formats (such [as this one](https://discourse.crowdsec.net/t/nginx-logs-in-gelf-json-format/53)), we're having to use to two different parsers. If the `grok` pattern could run on the result as an `expression`, it would make things a log simpler.

**Describe the solution you'd like**
Be able to run `grok` patterns on an expression result or something more than an existing field in `evt.Parsed`

**Comment by sabban** [comment]
I agree that it would be easier to manage this as this. 

But some remarks:
* Is the resulting stuff not too complex ?
* If we do this it should be possible to nest stuff, and I wonder if it's the way we want to go. (grok pattern inside an expression in a grok pattern in a expression, or do I miss sth) ?

**Comment by buixor** [comment]
I was thinking of extending the current syntax.

Currently the only support form is :

```yaml
grok:
      pattern: '... a grok pattern ...'
      apply_on: message
```

(where `apply_on` *has* to be an existing field of `evt.Parsed`)

To be as well supporting :

```yaml
grok:
      pattern: '... a grok pattern ...'
      expression: JsonExtract(evt.Parsed.msg, "foo.bar[0]")
```

Where `expression` could be any valid expression, while keeping backward compat.
