### ISSUE TITLE
Crowdsec not parsing apache error log

### ISSUE THREAD

**Issue by sbt2486** [crowdsecurity/crowdsec#831]
Hello

I'm trying to get crowdsec to parse my apache error and access logs. However, it's just only parsing the access logs for some reason. My aquisation config looks like this:

```
#Generated acquisition file - wizard.sh (service: apache2) / files : /var/log/apache2/error.log
filenames:
  - /var/log/apache2/error.log
  - /home/www/exmaple.com/logs/error.log
  - /home/www/example.com/logs/access.log
labels:
  type: apache2
---
#Generated acquisition file - wizard.sh (service: sshd) / files : /var/log/auth.log
filenames:
  - /var/log/auth.log
labels:
  type: syslog
---
#Generated acquisition file - wizard.sh (service: mysql) / files : /var/log/mysql/error.log
filenames:
  - /var/log/mysql/error.log
labels:
  type: mysql
---
#Generated acquisition file - wizard.sh (service: linux) / files : /var/log/syslog /var/log/messages
filenames:
  - /var/log/syslog
  - /var/log/messages
labels:
  type: syslog
---

```

Looking at the logs I can see that there is possibly something going wrong:

```
time="11-06-2021 05:23:13" level=info msg="[file datasource] opening file '/var/log/apache2/error.log'"
time="11-06-2021 05:23:13" level=info msg="[file datasource] opening file '/home/www/example.com/logs/error.log'"
time="11-06-2021 05:23:13" level=info msg="[file datasource] opening file '/home/www/example.com/logs/access.log'"
time="11-06-2021 05:23:13" level=info msg="[file datasource] opening file '/var/log/auth.log'"
time="11-06-2021 05:23:13" level=info msg="[file datasource] opening file '/var/log/mysql/error.log'"
time="11-06-2021 05:23:13" level=info msg="[file datasource] opening file '/var/log/syslog'"
time="11-06-2021 05:23:13" level=info msg="[file datasource] opening file '/var/log/messages'"
time="11-06-2021 05:23:13" level=warning msg="while configuring datasource : empty filename(s) and journalctl filter, malformed datasource"
```

cscli shows me that both error logs from aquisation config are not parsed at all:

```
+---------------------------------------+------------+--------------+----------------+------------------------+
|                SOURCE                 | LINES READ | LINES PARSED | LINES UNPARSED | LINES POURED TO BUCKET |
+---------------------------------------+------------+--------------+----------------+------------------------+
| /home/www/example.com/logs/access.log |     880807 |       880806 |              1 |                 270028 |
| /home/www/example.com/logs/error.log  |      20781 | -            |          20781 | -                      |
| /var/log/apache2/error.log            |         64 | -            |             64 | -                      |
| /var/log/auth.log                     |      10273 |           96 |          10177 |                    122 |
| /var/log/messages                     |        304 | -            |            304 | -                      |
| /var/log/mysql/error.log              |          2 | -            |              2 | -                      |
| /var/log/syslog                       |       6199 | -            |           6199 | -                      |
+---------------------------------------+------------+--------------+----------------+------------------------+
```

What am I doing wrong here? Why are `/home/www/example.com/logs/error.log` and `/var/log/apache2/error.log` not being parsed? Any help would be highly appreciated.
