### ISSUE TITLE
Improvement/Different Ban Times

### ISSUE THREAD

**Issue by haldrich** [crowdsecurity/crowdsec#863]
**Is your feature request related to a problem? Please describe.**
I'm trying to address an issue where, depending on what kind of reason a block decision was made, different times can be set for the ban... ie a SQL injection may have a 24 hour ban, a http-crawl ban might only be 10 minutes.

**Describe the solution you'd like**
I'd like to see an option so that we can (perhaps in profiles.yaml) indicate what the offending rule is and set the ban time based on that rule.  This would allow for proper setting of times based on the seriousness of the violation.

**Describe alternatives you've considered** (Optional) 
I looked in the docs to see if 'scope' in profiles.yaml worked this way, but the documentation is too sparse to understand the intended usage and if it would work for this scenario.  Trying it seemed to produce duplicate ban decision records.

**Example of what you imagine**
I imaging being able to set the section of the profiles.yaml with a value indicating the reason of the ban and having a time associated with the reason.

**Comment by buixor** [comment]
Hello @haldrich !

Thanks for the enhancement suggestion.

Yes, allowing the user to control more easily ban length duration is something that we want as well.

Currently, you can do something like :

```yaml
name: extraban_ip_remediation
filters:
 - Alert.Remediation == true && Alert.GetScope() == "Ip" && Alert.GetScenario() in ["crowdsecurity/ssh-bf", "foobar/toto"]
decisions:
 - type: ban
   duration: 8h
on_success: break
---
name: default_ip_remediation
#debug: true
filters:
 - Alert.Remediation == true && Alert.GetScope() == "Ip"
decisions:
 - type: ban
   duration: 4h
on_success: break
```
(this would make scenario `crowdsecurity/ssh-bf` and `foobar/toto` trigger a 8h ban instead of a 4h ban)

However, I do agree that it's not very convenient and the documentation is indeed too scarce.

We will try at least to improve the documentation of the profiles.yaml.
