### ISSUE TITLE
Improvement/Provide a cron that upgrades the hub and the collections/parsers/scenarios/....

### ISSUE THREAD

**Issue by blotus** [crowdsecurity/crowdsec#937]

**Comment by cmiscloni** [comment]
+1

**Comment by okohll** [comment]
Does

```
#!/bin/bash
cscli hub update
cscli hub upgrade
cscli collections upgrade -a
cscli parsers upgrade --all
cscli scenarios upgrade -a
systemctl reload crowdsec
```

about cover everything?

**Comment by mmetc** [comment]
There are still a few issues

 - crowdsec does not reload the configuration after hub upgrade
 - the package manager doesn't know about the cron job, so it won't be able to update it, or see if the user made changes
 - wizard.sh is soon going be a /bin/sh script - not bash - for compatibility with other distributions. It won't be called nor sourced from the postinst file. Also passing arguments to sourced files (the -n for noop) only works with bash

For these reasons, it would be better to follow each distribution's guidelines and install the cron job like we would install any other file:

 - https://fedoraproject.org/wiki/Packaging:CronFiles
 - https://www.debian.org/doc/manuals/maint-guide/dother.en.html#crond

A minimal cron.daily/crowdsec-hub would look like:

```
#!/bin/sh
cscli --error hub update && cscli --error hub upgrade
systemctl reload crowdsec
exit 0
```

I'm not convinced that systems installed with wizard.sh should have cron jobs, but if they do, they might not have systemd. That part is WIP.

What do you think? @sabban ?

**Comment by mridullpandey** [comment]
hi @mmetc i want to take this up..

**Comment by mmetc** [comment]
Hi @mridullpandey 

It's been merged here
https://github.com/crowdsecurity/crowdsec/blob/master/config/crowdsec.cron.daily

Any suggestion? We're releasing soon

Thanks

**Comment by tasiotas** [comment]
what about docker image?
could you include this cron in docker as well?

**Comment by mmetc** [comment]
@tasiotas there are several drawbacks to running a process manager and cron in a container, we'll try and find a better option

**Comment by jflattery** [comment]
> @tasiotas there are several drawbacks to running a process manager and cron in a container, we'll try and find a better option for both docker and k8s

Is there a issue that can be tracked for this? Is there a "proper" way to do this as of today?

**Comment by zc-devs** [comment]
Combining #3256 and Kubernetes Cron Job I was able to [import decisions via CLI](https://docs.crowdsec.net/docs/cscli/cscli_decisions_import/). Maybe you can do it for Hub updates.

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron
  namespace: crowdsec
spec:
  schedule: "1 1 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: cron
        spec:
          containers:
            - name: cron
              image: crowdsecurity/crowdsec:v1.6.3
              envFrom:
                - configMapRef:
                    name: cron-env
                - secretRef:
                    name: crowdsec-agent
              command:
                - "/bin/sh"
              args:
                - "/bin/cs-blocklists.sh"
              volumeMounts:
                - name: scripts
                  mountPath: /bin/cs-blocklists.sh
                  subPath: cs-blocklists.sh
          volumes:
            - name: scripts
              configMap:
                name: cron-file
```
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cron-env
  namespace: crowdsec
data:
  DISABLE_AGENT: "true"
  DISABLE_ONLINE_API: "true"
  DISABLE_LOCAL_API: "true"
  LOCAL_API_URL: http://lapi:8080
```
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cron-file
  namespace: crowdsec
data:
  cs-blocklists.sh: |
    ---
    #!/bin/sh

    /docker_start.sh

    blockLists='
    firehol-l1|https://iplists.firehol.org/files/firehol_level1.netset
    firehol-l2|https://iplists.firehol.org/files/firehol_level2.netset
    firehol-l3|https://iplists.firehol.org/files/firehol_level3.netset'

    echo "$blockLists" | while read -r blockList; do
      if [ -n "$blockList" ]; then
        listName=$(echo "$blockList" | cut -f 1 -d '|')
        echo "Processing $listName"
        listUrl=$(echo "$blockList" | cut -f 2 -d '|')
        listFileName="$listName.blocklist"
        wget "$listUrl" -O "$listFileName"

        echo "Importing single IPs from $listFileName"
        grep -E -i '^\d+\.\d+\.\d+\.\d+$' "$listFileName" > "$listFileName.ip"
        cscli decisions import --input "$listFileName.ip" --scope ip --duration 72h --reason "$listName" --format values
        rm -f "$listFileName.ip"

        echo "Importing ranges of IPs from $listFileName"
        grep -E -i '^\d+\.\d+\.\d+\.\d+/\d+$' "$listFileName" > "$listFileName.range"
        cscli decisions import --input "$listFileName.range" --scope range --duration 72h --reason "$listName" --format values
        rm -f "$listFileName.range"

        rm -f "$listFileName"
      fi
    done

    echo "Done"
```
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: crowdsec-agent
  namespace: crowdsec
stringData:
  AGENT_USERNAME: agent
  AGENT_PASSWORD: stub
```
